const fs = require('fs');
const path = require('path');

// Reference counts and CEFR alignments according to the official standardized HSK curriculum
const HSK_STANDARDS = {
  1: { level: 'HSK 1', cefr: 'A1', totalOfficiel: 150, title: 'HSK 1 — Vocabulaire Débutant (A1)', desc: 'Liste officielle standardisée de l’intégralité des 150 mots du HSK 1.' },
  2: { level: 'HSK 2', cefr: 'A2', totalOfficiel: 150, title: 'HSK 2 — Vocabulaire Pratique (A2)', desc: 'Liste officielle standardisée des 150 nouveaux mots du HSK 2 (total cumulé: 300 mots).' },
  3: { level: 'HSK 3', cefr: 'B1', totalOfficiel: 300, title: 'HSK 3 — Vocabulaire Intermédiaire (B1)', desc: 'Liste officielle standardisée des 300 nouveaux mots du HSK 3 (total cumulé: 600 mots).' },
  4: { level: 'HSK 4', cefr: 'B2', totalOfficiel: 600, title: 'HSK 4 — Vocabulaire Courant (B2)', desc: 'Liste officielle standardisée des 600 nouveaux mots du HSK 4 (total cumulé: 1200 mots).' },
  5: { level: 'HSK 5', cefr: 'C1', totalOfficiel: 1300, title: 'HSK 5 — Vocabulaire Avancé (C1)', desc: 'Liste officielle standardisée des 1300 nouveaux mots du HSK 5 (total cumulé: 2500 mots).' },
  6: { level: 'HSK 6', cefr: 'C2', totalOfficiel: 2500, title: 'HSK 6 — Vocabulaire Maîtrisé (C2)', desc: 'Liste officielle standardisée des 2500 nouveaux mots du HSK 6 (total cumulé: 5000 mots).' }
};

// Full Verified Official HSK 1 Word List (Exact 150 words)
const hsk1List = [
  { hanzi: '爱', pinyin: 'ài', french: 'Aimer / Amour', category: 'Sentiment', tip: 'Exprimer ses préférences pour un produit ou un service.' },
  { hanzi: '八', pinyin: 'bā', french: 'Huit (8)', category: 'Nombre', tip: 'Chiffre porte-bonheur absolu en Chine (symbole de prospérité 发财).' },
  { hanzi: '爸爸', pinyin: 'bàba', french: 'Papa / Père', category: 'Famille', tip: 'Vocabulaire relationnel et familial.' },
  { hanzi: '杯子', pinyin: 'bēizi', french: 'Verre / Tasse', category: 'Objet', tip: 'Indispensable lors de la dégustation de thé avec vos partenaires.' },
  { hanzi: '北京', pinyin: 'Běijīng', french: 'Pékin (Capitale)', category: 'Lieu', tip: 'Centre politique et culturel de la Chine.' },
  { hanzi: '本', pinyin: 'běn', french: 'Classificateur (livres, cahiers, catalogues)', category: 'Grammaire', tip: 'Utilisé pour compter les catalogues produits (一本产品手册).' },
  { hanzi: '不客气', pinyin: 'bù kèqi', french: 'De rien / Je vous en prie', category: 'Politesse', tip: 'Réponse polie universelle après un remerciement.' },
  { hanzi: '不', pinyin: 'bù', french: 'Non / Ne pas (négation)', category: 'Grammaire', tip: 'Négation du présent et du futur.' },
  { hanzi: '菜', pinyin: 'cài', french: 'Plat / Légume / Cuisine', category: 'Nourriture', tip: 'Les déjeuners d’affaires sont le cœur de la négociation en Chine.' },
  { hanzi: '茶', pinyin: 'chá', french: 'Thé', category: 'Boisson', tip: 'Boisson d’accueil servie à chaque rendez-vous professionnel.' },
  { hanzi: '吃', pinyin: 'chī', french: 'Manger', category: 'Action', tip: '« 你吃了吗？» est aussi une formule amicale de salutation.' },
  { hanzi: '出租车', pinyin: 'chūzūchē', french: 'Taxi', category: 'Transport', tip: 'Moyen de déplacement clé entre aéroports, usines et hôtels.' },
  { hanzi: '打电话', pinyin: 'dǎ diànhuà', french: 'Téléphoner / Passer un appel', category: 'Communication', tip: 'Prendre contact directement avec les fournisseurs.' },
  { hanzi: '大', pinyin: 'dà', french: 'Grand / Important', category: 'Adjectif', tip: 'Qualifier la taille d’un marché ou d’une usine (大工厂).' },
  { hanzi: '的', pinyin: 'de', french: 'Particule de possession / Qualification', category: 'Grammaire', tip: 'Relie le possesseur à l’objet (我的公司 = Mon entreprise).' },
  { hanzi: '点', pinyin: 'diǎn', french: 'Heure (horloge) / Point / Commander', category: 'Temps', tip: 'Fixer des heures précises de réunion (九点).' },
  { hanzi: '电脑', pinyin: 'diànnǎo', french: 'Ordinateur', category: 'Objet', tip: 'Outil central pour échanger e-mails et fiches techniques.' },
  { hanzi: '电视', pinyin: 'diànshì', french: 'Télévision', category: 'Objet', tip: 'Écran de présentation en salle de conférence.' },
  { hanzi: '电影', pinyin: 'diànyǐng', french: 'Film / Cinéma', category: 'Culture', tip: 'Sujet de conversation informel lors des dîners.' },
  { hanzi: '东西', pinyin: 'dōngxi', french: 'Chose / Objet / Article', category: 'Commerce', tip: 'Désigne les marchandises achetées (买东西).' },
  { hanzi: '都', pinyin: 'dōu', french: 'Tous / Tout', category: 'Grammaire', tip: 'Indique la totalité (我们都同意 = Nous sommes tous d’accord).' },
  { hanzi: '读', pinyin: 'dú', french: 'Lire / Étudier', category: 'Action', tip: 'Lire un document ou un contrat à haute voix.' },
  { hanzi: '对不起', pinyin: 'duìbuqǐ', french: 'Pardon / Désolé / Excusez-moi', category: 'Politesse', tip: 'Formule d’excuse courtoise en cas de retard ou d’imprévu.' },
  { hanzi: '多', pinyin: 'duō', french: 'Beaucoup / Nombreux', category: 'Quantité', tip: 'Commander en grande quantité (多买).' },
  { hanzi: '多少', pinyin: 'duōshao', french: 'Combien ?', category: 'Question', tip: 'Base de la négociation de prix (多少钱？).' },
  { hanzi: '儿子', pinyin: 'érzi', french: 'Fils', category: 'Famille', tip: 'Sujet familial valorisé dans la culture chinoise.' },
  { hanzi: '二', pinyin: 'èr', french: 'Deux (2)', category: 'Nombre', tip: 'Chiffre utilisé pour numéroter les étapes ou séries.' },
  { hanzi: '饭店', pinyin: 'fàndiàn', french: 'Restaurant / Hôtel', category: 'Lieu', tip: 'Lieu de réception et d’hébergement des délégations.' },
  { hanzi: '飞机', pinyin: 'fēijī', french: 'Avion', category: 'Transport', tip: 'Déplacements inter-villes rapides en Chine.' },
  { hanzi: '分钟', pinyin: 'fēnzhōng', french: 'Minute (durée)', category: 'Temps', tip: 'Indiquer un délai court (等五分钟 = attendre 5 minutes).' },
  { hanzi: '高兴', pinyin: 'gāoxìng', french: 'Heureux / Content / Ravi', category: 'Sentiment', tip: '« 很高兴认识你 » pour saluer un nouveau partenaire.' },
  { hanzi: '个', pinyin: 'gè', french: 'Classificateur général', category: 'Grammaire', tip: 'Le classificateur universel par excellence (一个样品).' },
  { hanzi: '工作', pinyin: 'gōngzuò', french: 'Travailler / Travail / Emploi', category: 'Profession', tip: 'Parler de ses projets et de son activité professionnelle.' },
  { hanzi: '狗', pinyin: 'gǒu', french: 'Chien', category: 'Animal', tip: 'Signe du zodiaque chinois.' },
  { hanzi: '汉语', pinyin: 'Hànyǔ', french: 'Langue chinoise / Mandarin', category: 'Langue', tip: 'Parler chinois ouvre toutes les portes dans les affaires.' },
  { hanzi: '好', pinyin: 'hǎo', french: 'Bon / Bien / D’accord', category: 'Adjectif', tip: 'Pour valider une proposition commerciale (好的).' },
  { hanzi: '喝', pinyin: 'hē', french: 'Boire', category: 'Action', tip: 'Boire le thé ou trinquer lors d’un banquet (干杯).' },
  { hanzi: '和', pinyin: 'hé', french: 'Et / Avec', category: 'Grammaire', tip: 'Liaison entre deux noms ou entités.' },
  { hanzi: '很', pinyin: 'hěn', french: 'Très', category: 'Degré', tip: 'Intensificateur devant un adjectif (很好 = Très bien).' },
  { hanzi: '后面', pinyin: 'hòumian', french: 'Derrière / À l’arrière', category: 'Position', tip: 'Indiquer la zone de stockage ou l’arrière-boutique.' },
  { hanzi: '回', pinyin: 'huí', french: 'Rentrer / Retourner', category: 'Action', tip: 'Rentrer à l’hôtel ou dans son pays (回国).' },
  { hanzi: '会', pinyin: 'huì', french: 'Savoir-faire / Pouvoir / Réunion', category: 'Capacité', tip: 'Exprimer une compétence acquise (我会说汉语).' },
  { hanzi: '几', pinyin: 'jǐ', french: 'Combien ? (petite quantité < 10) / Quelques', category: 'Question', tip: 'Demander le nombre de pièces ou de jours.' },
  { hanzi: '家', pinyin: 'jiā', french: 'Famille / Maison / Classificateur d’entreprise', category: 'Lieu', tip: 'Classificateur pour les usines et sociétés (一家公司).' },
  { hanzi: '叫', pinyin: 'jiào', french: 'S’appeler / Appeler', category: 'Action', tip: 'Se présenter lors d’un premier échange formel.' },
  { hanzi: '今天', pinyin: 'jīntiān', french: 'Aujourd’hui', category: 'Temps', tip: 'Fixer la date du jour pour une commande.' },
  { hanzi: '九', pinyin: 'jiǔ', french: 'Neuf (9)', category: 'Nombre', tip: 'Chiffre symbole de longévité et de durée.' },
  { hanzi: '开', pinyin: 'kāi', french: 'Ouvrir / Conduire / Démarrer', category: 'Action', tip: 'Démarrer une réunion ou ouvrir un compte (开会).' },
  { hanzi: '看', pinyin: 'kàn', french: 'Regarder / Voir / Examiner', category: 'Action', tip: 'Examiner les échantillons en salle d’exposition.' },
  { hanzi: '看见', pinyin: 'kànjiàn', french: 'Apercevoir / Voir', category: 'Action', tip: 'Constater visuellement un modèle ou un produit.' },
  { hanzi: '块', pinyin: 'kuài', french: 'Yuan / RMB (langage parlé)', category: 'Monnaie', tip: 'L’unité monétaire chinoise employée sur tous les marchés.' },
  { hanzi: '来', pinyin: 'lái', french: 'Venir / Arriver', category: 'Action', tip: 'Accueillir des visiteurs (欢迎来到中国).' },
  { hanzi: '老师', pinyin: 'lǎoshī', french: 'Enseignant / Maître / Mentor', category: 'Titre', tip: 'Titre de grand respect pour les experts et coachs.' },
  { hanzi: '了', pinyin: 'le', french: 'Particule d’accomplissement / Changement d’état', category: 'Grammaire', tip: 'Indique qu’une action est finalisée (做好了 = C’est prêt).' },
  { hanzi: '冷', pinyin: 'lěng', french: 'Froid', category: 'Météo', tip: 'Parler de la météo lors des voyages d’affaires en hiver.' },
  { hanzi: '里', pinyin: 'lǐ', french: 'Dans / À l’intérieur', category: 'Position', tip: 'Localiser un produit à l’intérieur du colis.' },
  { hanzi: '六', pinyin: 'liù', french: 'Six (6)', category: 'Nombre', tip: 'Chiffre porte-bonheur symbole de fluidité (六六大顺).' },
  { hanzi: '妈妈', pinyin: 'māma', french: 'Maman / Mère', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '吗', pinyin: 'ma', french: 'Particule interrogative finale', category: 'Grammaire', tip: 'Transforme n’importe quelle affirmation en question fermée.' },
  { hanzi: '买', pinyin: 'mǎi', french: 'Acheter', category: 'Commerce', tip: 'Le verbe roi de l’importateur et de l’acheteur.' },
  { hanzi: '猫', pinyin: 'māo', french: 'Chat', category: 'Animal', tip: 'Vocabulaire familier.' },
  { hanzi: '没关系', pinyin: 'méi guānxi', french: 'Ce n’est pas grave / Pas de problème', category: 'Politesse', tip: 'Dédramatiser courtoisement un petit contretemps.' },
  { hanzi: '没有', pinyin: 'méiyǒu', french: 'Ne pas avoir / Il n’y a pas', category: 'Négation', tip: 'Indiquer une rupture de stock ou l’absence d’un document.' },
  { hanzi: '米饭', pinyin: 'mǐfàn', french: 'Riz cuit', category: 'Nourriture', tip: 'L’aliment de base servi lors de chaque déjeuner.' },
  { hanzi: '明天', pinyin: 'míngtiān', french: 'Demain', category: 'Temps', tip: 'Planifier le rendez-vous du lendemain (明天见).' },
  { hanzi: '名字', pinyin: 'míngzi', french: 'Prénom / Nom / Nom de marque', category: 'Identité', tip: 'Enregistrer le nom d’un contact sur WeChat.' },
  { hanzi: '哪', pinyin: 'nǎ', french: 'Quel / Lequel ?', category: 'Question', tip: 'Sélectionner une option parmi plusieurs.' },
  { hanzi: '哪儿', pinyin: 'nǎr', french: 'Où ?', category: 'Question', tip: 'Demander l’adresse de l’usine ou de l’entrepôt.' },
  { hanzi: '那', pinyin: 'nà', french: 'Ce / Cet / Alors', category: 'Démonstratif', tip: 'Pointer un objet éloigné.' },
  { hanzi: '那儿', pinyin: 'nàr', french: 'Là-bas / Cet endroit', category: 'Lieu', tip: 'Désigner un emplacement sur le plan.' },
  { hanzi: '呢', pinyin: 'ne', french: 'Particule de relance (Et toi ? / Et ceci ?)', category: 'Grammaire', tip: 'Relancer une négociation en douceur (你呢？).' },
  { hanzi: '能', pinyin: 'néng', french: 'Pouvoir / Être en mesure de', category: 'Capacité', tip: 'Demander si une expédition est faisable (能不能发货？).' },
  { hanzi: '你', pinyin: 'nǐ', french: 'Tu / Toi', category: 'Pronom', tip: 'Pronom de base pour s’adresser à un collègue.' },
  { hanzi: '年', pinyin: 'nián', french: 'Année / An', category: 'Temps', tip: 'Dater les contrats et bons de commande.' },
  { hanzi: '女儿', pinyin: 'nǚ’ér', french: 'Fille', category: 'Famille', tip: 'Vocabulaire familial.' },
  { hanzi: '朋友', pinyin: 'péngyou', french: 'Ami / Partenaire relationnel', category: 'Relation', tip: 'Les affaires en Chine reposent sur l’amitié (做生意先做朋友).' },
  { hanzi: '漂亮', pinyin: 'piàoliang', french: 'Beau / Joli / Remarquable', category: 'Appréciation', tip: 'Complimenter le design d’un nouveau produit.' },
  { hanzi: '苹果', pinyin: 'píngguǒ', french: 'Pomme', category: 'Nourriture', tip: 'Fruit populaire offert lors des visites.' },
  { hanzi: '七', pinyin: 'qī', french: 'Sept (7)', category: 'Nombre', tip: 'Chiffre utilisé pour les calendriers et quantités.' },
  { hanzi: '前面', pinyin: 'qiánmian', french: 'Devant / En face', category: 'Position', tip: 'Guider un chauffeur vers l’entrée principale.' },
  { hanzi: '钱', pinyin: 'qián', french: 'Argent / Monnaie', category: 'Commerce', tip: 'Terme central pour les transactions et règlements.' },
  { hanzi: '请', pinyin: 'qǐng', french: 'S’il vous plaît / Inviter / Prier de', category: 'Politesse', tip: 'Formule de politesse indispensable (请坐 = Asseyez-vous svp).' },
  { hanzi: '去', pinyin: 'qù', french: 'Aller / Se rendre à', category: 'Action', tip: 'Se rendre à la foire de Canton ou au port.' },
  { hanzi: '热', pinyin: 'rè', french: 'Chaud / Chaleureux', category: 'Météo', tip: 'Demander de l’eau chaude (热茶 / 热水).' },
  { hanzi: '人', pinyin: 'rén', french: 'Personne / Homme / Être humain', category: 'Société', tip: 'Désigne la population ou l’interlocuteur (中国人 / 法国人).' },
  { hanzi: '认识', pinyin: 'rènshi', french: 'Connaître / Faire la connaissance', category: 'Relation', tip: 'Créer de nouveaux réseaux professionnels.' },
  { hanzi: '三', pinyin: 'sān', french: 'Trois (3)', category: 'Nombre', tip: 'Chiffre utilisé dans les séries de production.' },
  { hanzi: '商店', pinyin: 'shāngdiàn', french: 'Magasin / Boutique', category: 'Lieu', tip: 'Point de vente physique ou showroom.' },
  { hanzi: '上', pinyin: 'shàng', french: 'Sur / En haut / Monter / Précédent', category: 'Position', tip: 'Poser sur la table de négociation.' },
  { hanzi: '上午', pinyin: 'shàngwǔ', french: 'Matin / Matinée', category: 'Temps', tip: 'Le meilleur créneau pour les visites d’usines.' },
  { hanzi: '少', pinyin: 'shǎo', french: 'Peu / Moins / Rare', category: 'Quantité', tip: 'Qualifier un petit volume de commande.' },
  { hanzi: '谁', pinyin: 'shéi / shuí', french: 'Qui ?', category: 'Question', tip: 'Identifier le responsable décisionnaire d’une société.' },
  { hanzi: '什么', pinyin: 'shénme', french: 'Quoi ? / Quel ?', category: 'Question', tip: 'Demander les caractéristiques d’un article (这是什么？).' },
  { hanzi: '十', pinyin: 'shí', french: 'Dix (10)', category: 'Nombre', tip: 'Base décimale de calcul des prix et remises.' },
  { hanzi: '时候', pinyin: 'shíhou', french: 'Moment / Époque', category: 'Temps', tip: '« 什么时候 » pour convenir d’une date de livraison.' },
  { hanzi: '是', pinyin: 'shì', french: 'Être / Oui / En effet', category: 'Verbe', tip: 'Verbe d’affirmation et d’identification.' },
  { hanzi: '书', pinyin: 'shū', french: 'Livre / Manuel', category: 'Objet', tip: 'Documents et manuels d’utilisation de machines.' },
  { hanzi: '水', pinyin: 'shuǐ', french: 'Eau', category: 'Boisson', tip: 'Indispensable lors des longues journées de salon.' },
  { hanzi: '水果', pinyin: 'shuǐguǒ', french: 'Fruit', category: 'Nourriture', tip: 'Cadeau de courtoisie fréquent lors des rencontres.' },
  { hanzi: '睡觉', pinyin: 'shuìjiào', french: 'Dormir / Se coucher', category: 'Vie', tip: 'Gestion du décalage horaire lors des voyages en Asie.' },
  { hanzi: '说', pinyin: 'shuō', french: 'Parler / Dire / Expliquer', category: 'Action', tip: 'Exprimer ses besoins commerciaux en direct.' },
  { hanzi: '说话', pinyin: 'shuōhuà', french: 'Parler / Discuter / Échanger', category: 'Communication', tip: 'Discuter des termes d’un partenariat.' },
  { hanzi: '四', pinyin: 'sì', french: 'Quatre (4)', category: 'Nombre', tip: 'Chiffre homophone du mot mort, évité dans certains prix.' },
  { hanzi: '岁', pinyin: 'suì', french: 'Âge / Ans (pour une personne)', category: 'Identité', tip: 'Vocabulaire descriptif de profil.' },
  { hanzi: '他', pinyin: 'tā', french: 'Il / Lui', category: 'Pronom', tip: 'Désigne un interlocuteur masculin ou une tierce personne.' },
  { hanzi: '她', pinyin: 'tā', french: 'Elle', category: 'Pronom', tip: 'Désigne une interlocutrice féminine.' },
  { hanzi: '太', pinyin: 'tài', french: 'Trop / Extrêmement', category: 'Degré', tip: 'Exprimer l’enthousiasme (太好了 = C’est formidable).' },
  { hanzi: '天气', pinyin: 'tiānqì', french: 'Météo / Temps qu’il fait', category: 'Météo', tip: 'Sujet parfait pour briser la glace avant une réunion.' },
  { hanzi: '听', pinyin: 'tīng', french: 'Écouter / Entendre', category: 'Action', tip: 'Écouter attentivement les propositions d’un fournisseur.' },
  { hanzi: '同学', pinyin: 'tóngxué', french: 'Camarade de classe / Condisciple', category: 'Éducation', tip: 'Réseau d’anciens élèves très puissant en Chine (校友).' },
  { hanzi: '喂', pinyin: 'wèi', french: 'Allô ? / Hé !', category: 'Communication', tip: 'Mot d’ouverture de tout appel téléphonique en Chine.' },
  { hanzi: '我', pinyin: 'wǒ', french: 'Je / Moi', category: 'Pronom', tip: 'Pronom personnel fondamental.' },
  { hanzi: '我们', pinyin: 'wǒmen', french: 'Nous', category: 'Pronom', tip: 'Désigne l’équipe ou les deux parties au contrat.' },
  { hanzi: '五', pinyin: 'wǔ', french: 'Cinq (5)', category: 'Nombre', tip: 'Chiffre clé pour les jours de travail ouvrés.' },
  { hanzi: '喜欢', pinyin: 'xǐhuan', french: 'Aimer / Apprécier', category: 'Sentiment', tip: 'Exprimer son intérêt pour une gamme de produits.' },
  { hanzi: '下', pinyin: 'xià', french: 'Sous / En bas / Descendre / Suivant', category: 'Position', tip: 'Indique la semaine prochaine (下个星期).' },
  { hanzi: '下午', pinyin: 'xiàwǔ', french: 'Après-midi', category: 'Temps', tip: 'Créneau idéal pour la signature des accords.' },
  { hanzi: '下雨', pinyin: 'xiàyǔ', french: 'Pleuvoir / Il pleut', category: 'Météo', tip: 'Vocabulaire météo.' },
  { hanzi: '先生', pinyin: 'xiānsheng', french: 'Monsieur / Époux', category: 'Titre', tip: 'Titre honorifique placé après le nom (王先生).' },
  { hanzi: '现在', pinyin: 'xiànzài', french: 'Maintenant / Actuellement', category: 'Temps', tip: 'Insister sur l’urgence d’une commande ou d’un virement.' },
  { hanzi: '想', pinyin: 'xiǎng', french: 'Vouloir / Penser / Souhaiter', category: 'Volonté', tip: 'Exprimer une intention d’achat (我想买).' },
  { hanzi: '小', pinyin: 'xiǎo', french: 'Petit / Modeste', category: 'Adjectif', tip: 'Qualifier un échantillon ou une commande d’essai.' },
  { hanzi: '小姐', pinyin: 'xiǎojiě', french: 'Mademoiselle / Jeune femme', category: 'Titre', tip: 'Titre de politesse (陈小姐).' },
  { hanzi: '些', pinyin: 'xiē', french: 'Quelques / Des / Un peu', category: 'Quantité', tip: 'Indiquer un groupe d’articles (这些产品).' },
  { hanzi: '写', pinyin: 'xiě', french: 'Écrire / Rédiger', category: 'Action', tip: 'Rédiger une facture proforma ou une clause.' },
  { hanzi: '谢谢', pinyin: 'xièxie', french: 'Merci / Remercier', category: 'Politesse', tip: 'Formule universelle de gratitude.' },
  { hanzi: '星期', pinyin: 'xīngqī', french: 'Semaine', category: 'Temps', tip: 'Organiser l’emploi du temps et les délais de production.' },
  { hanzi: '学生', pinyin: 'xuésheng', french: 'Étudiant / Élève', category: 'Éducation', tip: 'Apprenant de la langue chinoise.' },
  { hanzi: '学习', pinyin: 'xuéxí', french: 'Apprendre / Étudier', category: 'Éducation', tip: 'Se perfectionner en mandarin des affaires.' },
  { hanzi: '学校', pinyin: 'xuéxiào', french: 'École / Université / Institut', category: 'Lieu', tip: 'Lieu d’apprentissage et de formation.' },
  { hanzi: '一', pinyin: 'yī', french: 'Un (1)', category: 'Nombre', tip: 'Base de tout calcul et de toute négociation.' },
  { hanzi: '一点儿', pinyin: 'yīdiǎnr', french: 'Un peu / Un petit peu', category: 'Quantité', tip: 'Demander un geste commercial (便宜一点儿).' },
  { hanzi: '衣服', pinyin: 'yīfu', french: 'Vêtement / Textile', category: 'Produit', tip: 'Secteur d’importation textile très majeur.' },
  { hanzi: '医生', pinyin: 'yīshēng', french: 'Médecin / Docteur', category: 'Profession', tip: 'Vocabulaire santé lors des déplacements.' },
  { hanzi: '医院', pinyin: 'yīyuàn', french: 'Hôpital', category: 'Lieu', tip: 'Infrastructure médicale d’urgence.' },
  { hanzi: '椅子', pinyin: 'yǐzi', french: 'Chaise', category: 'Mobilier', tip: 'Secteur du mobilier et aménagement de bureau.' },
  { hanzi: '有', pinyin: 'yǒu', french: 'Avoir / Il y a / Posséder', category: 'Verbe', tip: 'Vérifier la disponibilité en stock (有没有现货？).' },
  { hanzi: '月', pinyin: 'yuè', french: 'Mois / Lune', category: 'Temps', tip: 'Indiquer le mois de livraison contractuel.' },
  { hanzi: '再见', pinyin: 'zàijiàn', french: 'Au revoir', category: 'Salutation', tip: 'Clôturer un entretien professionnel sur une note positive.' },
  { hanzi: '在', pinyin: 'zài', french: 'Être à / Présent / En train de', category: 'Grammaire', tip: 'Indique la localisation ou l’action continue.' },
  { hanzi: '怎么', pinyin: 'zěnme', french: 'Comment ? / Pourquoi ?', category: 'Question', tip: 'Demander le fonctionnement d’une machine (怎么用？).' },
  { hanzi: '怎么样', pinyin: 'zěnmeyàng', french: 'Comment est-ce ? / Qu’en pensez-vous ?', category: 'Question', tip: 'Recueillir l’avis d’un partenaire sur un prix ou contrat.' },
  { hanzi: '这', pinyin: 'zhè', french: 'Ce / Cet / Ceci', category: 'Démonstratif', tip: 'Désigner le produit en main (这个).' },
  { hanzi: '这儿', pinyin: 'zhèr', french: 'Ici / Cet endroit', category: 'Lieu', tip: 'Désigner l’emplacement actuel.' },
  { hanzi: '中国', pinyin: 'Zhōngguó', french: 'Chine', category: 'Pays', tip: 'Première puissance manufacturière mondiale.' },
  { hanzi: '中午', pinyin: 'zhōngwǔ', french: 'Midi / Milieu de journée', category: 'Temps', tip: 'Pause déjeuner et détente.' },
  { hanzi: '住', pinyin: 'zhù', french: 'Habiter / Résider / Loger', category: 'Action', tip: 'Loger à l’hôtel lors d’un séjour d’affaires.' },
  { hanzi: '桌子', pinyin: 'zhuōzi', french: 'Table / Bureau', category: 'Mobilier', tip: 'Mobilier de négociation et réunion.' },
  { hanzi: '字', pinyin: 'zì', french: 'Caractère / Sinogramme / Écriture', category: 'Écriture', tip: 'Les caractères chinois (汉字).' },
  { hanzi: '昨天', pinyin: 'zuótiān', french: 'Hier', category: 'Temps', tip: 'Faire référence aux échanges de la veille.' },
  { hanzi: '坐', pinyin: 'zuò', french: 'S’asseoir / Prendre (un transport)', category: 'Action', tip: 'Prendre l’avion ou le train (坐飞机 / 坐高铁).' },
  { hanzi: '做', pinyin: 'zuò', french: 'Faire / Fabriquer / Produire', category: 'Action', tip: 'Faire du commerce international (做生意).' },
];

// Full Verified Official HSK 2 Word List (Exact 150 words)
const hsk2List = [
  { hanzi: '吧', pinyin: 'ba', french: 'Particule de suggestion / Accord', category: 'Grammaire', tip: 'Valider une proposition de prix en douceur.' },
  { hanzi: '白', pinyin: 'bái', french: 'Blanc / En vain', category: 'Couleur', tip: 'Couleur de produit ou emballage.' },
  { hanzi: '百', pinyin: 'bǎi', french: 'Cent (100)', category: 'Nombre', tip: 'Commandes par centaines d’unités.' },
  { hanzi: '帮助', pinyin: 'bāngzhù', french: 'Aider / Assistance / Soutien', category: 'Verbe', tip: 'Assistance technique fournie par l’usine.' },
  { hanzi: '报纸', pinyin: 'bàozhǐ', french: 'Journal / Presse', category: 'Média', tip: 'Actualités économiques.' },
  { hanzi: '比', pinyin: 'bǐ', french: 'Comparer / Plus que', category: 'Grammaire', tip: 'Comparer deux offres de fabricants.' },
  { hanzi: '别', pinyin: 'bié', french: 'Ne pas / Autre', category: 'Négation', tip: 'Éviter les erreurs de marquage.' },
  { hanzi: '长', pinyin: 'cháng', french: 'Long / Durée', category: 'Adjectif', tip: 'Partenariat à long terme (长期合作).' },
  { hanzi: '唱歌', pinyin: 'chàng gē', french: 'Chanter / Soirée KTV', category: 'Loisir', tip: 'Le KTV (karaoké) est un lieu classique de négociation en Chine.' },
  { hanzi: '出', pinyin: 'chū', french: 'Sortir / Exporter / Émettre', category: 'Verbe', tip: 'Expédier la marchandise d’usine (出货).' },
  { hanzi: '穿', pinyin: 'chuān', french: 'Porter / S’habiller', category: 'Verbe', tip: 'Équipement de sécurité obligatoire en usine.' },
  { hanzi: '次', pinyin: 'cì', french: 'Fois / Ordre', category: 'Classificateur', tip: 'Cette première commande (这次订单).' },
  { hanzi: '从', pinyin: 'cóng', french: 'Depuis / De / À partir de', category: 'Préposition', tip: 'Port de départ maritime (从宁波港出发).' },
  { hanzi: '错', pinyin: 'cuò', french: 'Erreur / Faux / Pas mal (不错)', category: 'Adjectif', tip: 'Complimenter la qualité (质量很不错).' },
  { hanzi: '打篮球', pinyin: 'dǎ lánqiú', french: 'Jouer au basket-ball', category: 'Sport', tip: 'Sport très populaire parmi les jeunes entrepreneurs en Chine.' },
  { hanzi: '大家', pinyin: 'dàjiā', french: 'Tout le monde / Tous ensemble', category: 'Pronom', tip: 'S’adresser à toute l’équipe.' },
  { hanzi: '到', pinyin: 'dào', french: 'Arriver / Jusqu’à / Atteindre', category: 'Verbe', tip: 'Arrivée du navire au port de destination.' },
  { hanzi: '得', pinyin: 'de', french: 'Particule d’appréciation du résultat', category: 'Grammaire', tip: 'Production très rapide (做得很快).' },
  { hanzi: '等', pinyin: 'děng', french: 'Attendre / Et cætera', category: 'Verbe', tip: 'Attendre la confirmation du paiement.' },
  { hanzi: '弟弟', pinyin: 'dìdi', french: 'Petit frère', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '第一', pinyin: 'dì-yī', french: 'Premier / Numéro 1', category: 'Nombre', tip: 'La qualité d’abord (质量第一).' },
  { hanzi: '懂', pinyin: 'dǒng', french: 'Comprendre / Maîtriser', category: 'Verbe', tip: 'Comprendre les spécificités techniques.' },
  { hanzi: '对', pinyin: 'duì', french: 'Correct / Envers / Face à', category: 'Adjectif', tip: 'Validation formelle des documents.' },
  { hanzi: '房间', pinyin: 'fángjiān', french: 'Chambre / Pièce / Salle', category: 'Lieu', tip: 'Salle de réunion ou showroom d’usine.' },
  { hanzi: '非常', pinyin: 'fēicháng', french: 'Extrêmement / Très', category: 'Adverbe', tip: 'Marquer un grand intérêt commercial.' },
  { hanzi: '服务员', pinyin: 'fúwùyuán', french: 'Serveur / Personnel d’accueil', category: 'Profession', tip: 'Commander lors des déjeuners professionnels.' },
  { hanzi: '高', pinyin: 'gāo', french: 'Haut / Élevé / Grand', category: 'Adjectif', tip: 'Haute qualité (高质量).' },
  { hanzi: '告诉', pinyin: 'gàosu', french: 'Informer / Dire à quelqu’un', category: 'Verbe', tip: 'Communiquer les dimensions ou quantités.' },
  { hanzi: '哥哥', pinyin: 'gēge', french: 'Grand frère', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '给', pinyin: 'gěi', french: 'Donner / Accorder / Pour', category: 'Verbe', tip: 'Accorder un tarif préférentiel (给优惠).' },
  { hanzi: '公共汽车', pinyin: 'gōnggòng qìchē', french: 'Bus public / Autobus', category: 'Transport', tip: 'Transports en commun urbains.' },
  { hanzi: '公司', pinyin: 'gōngsī', french: 'Entreprise / Société / Compagnie', category: 'Commerce', tip: 'Le terme clé pour désigner votre entreprise importatrice.' },
  { hanzi: '贵', pinyin: 'guì', french: 'Cher / Précieux / Honorifique', category: 'Adjectif', tip: 'Votre honorable entreprise (贵公司).' },
  { hanzi: '过', pinyin: 'guò', french: 'Passer / Traverser / Particule d’expérience', category: 'Grammaire', tip: 'Avoir déjà visité cette usine (去过这家工厂).' },
  { hanzi: '还', pinyin: 'hái', french: 'Encore / En plus / Toujours', category: 'Adverbe', tip: 'Commander des articles supplémentaires.' },
  { hanzi: '孩子', pinyin: 'háizi', french: 'Enfant', category: 'Famille', tip: 'Vocabulaire familial.' },
  { hanzi: '好吃', pinyin: 'hǎochī', french: 'Délicieux / Bon à manger', category: 'Nourriture', tip: 'Complimenter les spécialités locales lors d’un banquet.' },
  { hanzi: '黑', pinyin: 'hēi', french: 'Noir / Sombre', category: 'Couleur', tip: 'Couleur de boîtier ou produit.' },
  { hanzi: '红', pinyin: 'hóng', french: 'Rouge / Populaire', category: 'Couleur', tip: 'Couleur symbole de chance et succès en Chine.' },
  { hanzi: '欢迎', pinyin: 'huānyíng', french: 'Bienvenue / Accueillir chaleureusement', category: 'Politesse', tip: 'Accueillir des partenaires étrangers.' },
  { hanzi: '回答', pinyin: 'huídá', french: 'Répondre / Réponse', category: 'Action', tip: 'Répondre formellement à un appel d’offres.' },
  { hanzi: '机场', pinyin: 'jīchǎng', french: 'Aéroport', category: 'Lieu', tip: 'Point d’arrivée des délégations.' },
  { hanzi: '鸡蛋', pinyin: 'jīdàn', french: 'Œuf', category: 'Nourriture', tip: 'Alimentation du quotidien.' },
  { hanzi: '件', pinyin: 'jiàn', french: 'Classificateur de pièce / Vêtement / Affaire', category: 'Classificateur', tip: 'Une pièce de marchandise (一件货物).' },
  { hanzi: '教室', pinyin: 'jiàoshì', french: 'Salle de classe', category: 'Lieu', tip: 'Lieu d’apprentissage.' },
  { hanzi: '姐姐', pinyin: 'jiějie', french: 'Grande sœur', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '介绍', pinyin: 'jièshào', french: 'Présenter / Recommander / Introduction', category: 'Action', tip: 'Présenter un fournisseur ou un transitaire.' },
  { hanzi: '进', pinyin: 'jìn', french: 'Entrer / Importer (进货)', category: 'Commerce', tip: 'Approvisionnement et réassort (进货).' },
  { hanzi: '近', pinyin: 'jìn', french: 'Proche / Près', category: 'Position', tip: 'Proximité du port maritime.' },
  { hanzi: '就', pinyin: 'jiù', french: 'Aussitôt / Dès lors / Justement', category: 'Adverbe', tip: 'Livraison immédiate.' },
  { hanzi: '觉得', pinyin: 'juéde', french: 'Penser / Trouver / Ressentir', category: 'Opinion', tip: 'Donner son avis sur la qualité d’un échantillon.' },
  { hanzi: '咖啡', pinyin: 'kāfēi', french: 'Café', category: 'Boisson', tip: 'Pause café lors des réunions d’affaires.' },
  { hanzi: '开始', pinyin: 'kāishǐ', french: 'Commencer / Débuter / Lancement', category: 'Action', tip: 'Lancement officiel de la fabrication en série.' },
  { hanzi: '考试', pinyin: 'kǎoshì', french: 'Examen / Test / Épreuve', category: 'Éducation', tip: 'Certification officielle HSK.' },
  { hanzi: '可能', pinyin: 'kěnéng', french: 'Peut-être / Possible / Probable', category: 'Probabilité', tip: 'Évaluer la faisabilité d’une demande spéciale.' },
  { hanzi: '可以', pinyin: 'kěyǐ', french: 'Pouvoir / C’est possible / Autorisé', category: 'Accord', tip: 'Valider une condition de paiement.' },
  { hanzi: '课', pinyin: 'kè', french: 'Leçon / Cours', category: 'Éducation', tip: 'Module de formation.' },
  { hanzi: '快', pinyin: 'kuài', french: 'Rapide / Bientôt', category: 'Vitesse', tip: 'Délais de fabrication express.' },
  { hanzi: '快乐', pinyin: 'kuàilè', french: 'Joyeux / Bonheur', category: 'Sentiment', tip: 'Souhaiter de bonnes fêtes (新年快乐).' },
  { hanzi: '累', pinyin: 'lèi', french: 'Fatigué', category: 'État', tip: 'Après une longue journée de visites.' },
  { hanzi: '离', pinyin: 'lí', french: 'Distant de / Éloigné de', category: 'Distance', tip: 'Calculer la distance entre l’usine et le port.' },
  { hanzi: '两', pinyin: 'liǎng', french: 'Deux (devant un spécificatif)', category: 'Nombre', tip: 'Deux conteneurs (两个集装箱).' },
  { hanzi: '零', pinyin: 'líng', french: 'Zéro (0)', category: 'Nombre', tip: 'Chiffre des calculs financiers.' },
  { hanzi: '路', pinyin: 'lù', french: 'Route / Chemin / Ligne de transport', category: 'Transport', tip: 'Itinéraire logistique (陆运).' },
  { hanzi: '旅游', pinyin: 'lǚyóu', french: 'Voyager / Tourisme', category: 'Voyage', tip: 'Découverte des grandes villes industrielles.' },
  { hanzi: '卖', pinyin: 'mài', french: 'Vendre', category: 'Commerce', tip: 'Vente au détail et distribution.' },
  { hanzi: '慢', pinyin: 'màn', french: 'Lent / Doucement', category: 'Vitesse', tip: 'Prendre le temps d’examiner chaque détail.' },
  { hanzi: '忙', pinyin: 'máng', french: 'Occupé / En pleine activité', category: 'État', tip: 'Haute saison de production en usine.' },
  { hanzi: '每', pinyin: 'měi', french: 'Chaque / Tout', category: 'Quantité', tip: 'Prix unitaire (每个单价).' },
  { hanzi: '妹妹', pinyin: 'mèimei', french: 'Petite sœur', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '门', pinyin: 'mén', french: 'Porte / Entrée', category: 'Lieu', tip: 'Porte d’entrée de l’usine.' },
  { hanzi: '男人', pinyin: 'nánrén', french: 'Homme', category: 'Société', tip: 'Profil démographique.' },
  { hanzi: '您', pinyin: 'nín', french: 'Vous (forme polie de respect)', category: 'Politesse', tip: 'La forme indispensable pour s’adresser aux directeurs d’usines.' },
  { hanzi: '牛奶', pinyin: 'niúnǎi', french: 'Lait', category: 'Boisson', tip: 'Alimentation.' },
  { hanzi: '女人', pinyin: 'nǚrén', french: 'Femme', category: 'Société', tip: 'Profil démographique.' },
  { hanzi: '旁边', pinyin: 'pángbiān', french: 'À côté / À proximité', category: 'Position', tip: 'Zone adjacente à l’atelier de contrôle qualité.' },
  { hanzi: '跑步', pinyin: 'pǎobù', french: 'Courir / Jogging', category: 'Sport', tip: 'Hygiène de vie.' },
  { hanzi: '便宜', pinyin: 'piányi', french: 'Bon marché / Avantageux / Économique', category: 'Prix', tip: 'Négocier un meilleur tarif d’achat.' },
  { hanzi: '票', pinyin: 'piào', french: 'Billet / Ticket / Facturette', category: 'Document', tip: 'Billet de train à grande vitesse (高铁票).' },
  { hanzi: '妻子', pinyin: 'qīzi', french: 'Épouse / Femme', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '起床', pinyin: 'qǐchuáng', french: 'Se lever / Sortir du lit', category: 'Vie', tip: 'Commencer tôt sa journée de sourcing.' },
  { hanzi: '千', pinyin: 'qiān', french: 'Mille (1 000)', category: 'Nombre', tip: 'Commandes par milliers d’unités (一千件).' },
  { hanzi: '晴', pinyin: 'qíng', french: 'Ensoleillé / Beau temps', category: 'Météo', tip: 'Conditions météo idéales.' },
  { hanzi: '去年', pinyin: 'qùnián', french: 'L’année dernière', category: 'Temps', tip: 'Comparer avec le volume de l’exercice précédent.' },
  { hanzi: '让', pinyin: 'ràng', french: 'Laisser / Permettre / Faire faire', category: 'Verbe', tip: 'Faire vérifier par le transitaire.' },
  { hanzi: '日', pinyin: 'rì', french: 'Jour / Date officielle / Soleil', category: 'Temps', tip: 'Date formelle sur les factures et connaissements.' },
  { hanzi: '上班', pinyin: 'shàngbān', french: 'Aller au travail / Prendre son service', category: 'Profession', tip: 'Heures d’ouverture des bureaux en Chine.' },
  { hanzi: '身体', pinyin: 'shēntǐ', french: 'Corps / Santé', category: 'Santé', tip: 'Souhaiter une excellente santé à ses partenaires (身体健康).' },
  { hanzi: '生病', pinyin: 'shēngbìng', french: 'Tomber malade', category: 'Santé', tip: 'Imprévu de santé.' },
  { hanzi: '生日', pinyin: 'shēngrì', french: 'Anniversaire', category: 'Événement', tip: 'Attention relationnelle très appréciée en Chine.' },
  { hanzi: '时间', pinyin: 'shíjiān', french: 'Temps / Durée / Horaire', category: 'Temps', tip: 'Respect des délais de fabrication (交货时间).' },
  { hanzi: '事情', pinyin: 'shìqing', french: 'Affaire / Dossier / Événement', category: 'Affaires', tip: 'Régler un dossier commercial important.' },
  { hanzi: '手表', pinyin: 'shǒubiǎo', french: 'Montre / Horlogerie', category: 'Produit', tip: 'Secteur des accessoires et de l’horlogerie.' },
  { hanzi: '手机', pinyin: 'shǒujī', french: 'Téléphone portable / Smartphone', category: 'Technologie', tip: 'Outil indispensable pour les paiements WeChat Pay / Alipay.' },
  { hanzi: '送', pinyin: 'sòng', french: 'Offrir / Livrer / Raccompagner', category: 'Action', tip: 'Offrir un cadeau d’entreprise ou livrer des échantillons.' },
  { hanzi: '虽然', pinyin: 'suīrán', french: 'Bien que / Quoique', category: 'Grammaire', tip: 'Articuler une négociation nuancée (虽然...但是...).' },
  { hanzi: '但是', pinyin: 'dànshì', french: 'Mais / Cependant', category: 'Conjonction', tip: 'Introduire un compromis commercial.' },
  { hanzi: '它', pinyin: 'tā', french: 'Il / Elle (pour les objets ou animaux)', category: 'Pronom', tip: 'Désigner une marchandise.' },
  { hanzi: '踢足球', pinyin: 'tī zúqiú', french: 'Jouer au football', category: 'Sport', tip: 'Sport mondial fédérateur.' },
  { hanzi: '题', pinyin: 'tí', french: 'Question / Sujet / Problème', category: 'Éducation', tip: 'Exercice du test HSK.' },
  { hanzi: '跳舞', pinyin: 'tiàowǔ', french: 'Danser', category: 'Culture', tip: 'Spectacles culturels.' },
  { hanzi: '外', pinyin: 'wài', french: 'Extérieur / Étranger (外贸)', category: 'Commerce', tip: 'Commerce international (外贸 wàimào).' },
  { hanzi: '完', pinyin: 'wán', french: 'Terminer / Finir / Complètement', category: 'Action', tip: 'Achèvement total de la production.' },
  { hanzi: '玩', pinyin: 'wán', french: 'Jouer / S’amuser / Se détendre', category: 'Loisir', tip: 'Moments de convivialité après la négociation.' },
  { hanzi: '晚上', pinyin: 'wǎnshang', french: 'Soir / Soirée', category: 'Temps', tip: 'Banquet officiel de clôture de contrat.' },
  { hanzi: '往', pinyin: 'wǎng', french: 'Vers / En direction de', category: 'Direction', tip: 'Expédition vers les ports d’Afrique.' },
  { hanzi: '为什么', pinyin: 'wèishénme', french: 'Pourquoi ?', category: 'Question', tip: 'Demander l’origine d’un retard logistique.' },
  { hanzi: '问', pinyin: 'wèn', french: 'Demander / Poser une question', category: 'Action', tip: 'Demander un devis actualisé.' },
  { hanzi: '问题', pinyin: 'wèntí', french: 'Problème / Question / Difficulté', category: 'Affaires', tip: '« 没问题 » (aucun problème) pour rassurer un client.' },
  { hanzi: '西瓜', pinyin: 'xīguā', french: 'Pastèque', category: 'Nourriture', tip: 'Fruit offert en été dans les usines.' },
  { hanzi: '希望', pinyin: 'xīwàng', french: 'Espérer / Souhait / Espoir', category: 'Volonté', tip: 'Partager une ambition commune de croissance.' },
  { hanzi: '洗', pinyin: 'xǐ', french: 'Laver / Nettoyer', category: 'Action', tip: 'Instructions d’entretien sur les étiquettes textiles.' },
  { hanzi: '小时', pinyin: 'xiǎoshí', french: 'Heure (durée)', category: 'Temps', tip: 'Nombre d’heures de vol ou de transport.' },
  { hanzi: '笑', pinyin: 'xiào', french: 'Sourire / Rire', category: 'Attitude', tip: 'Un sourire chaleureux facilite grandement les négociations.' },
  { hanzi: '新', pinyin: 'xīn', french: 'Nouveau / Neuf / Récent', category: 'Produit', tip: 'Nouveaux modèles et innovations (新产品).' },
  { hanzi: '姓', pinyin: 'xìng', french: 'Nom de famille / Se nommer', category: 'Identité', tip: 'Demander poliment le nom de famille (您贵姓？).' },
  { hanzi: '休息', pinyin: 'xiūxi', french: 'Se reposer / Pause', category: 'Vie', tip: 'Pause café pendant les réunions techniques.' },
  { hanzi: '雪', pinyin: 'xuě', french: 'Neige', category: 'Météo', tip: 'Conditions climatiques d’hiver dans le Nord de la Chine.' },
  { hanzi: '颜色', pinyin: 'yánsè', french: 'Couleur', category: 'Design', tip: 'Choisir les teintes exactes selon le nuancier Pantone.' },
  { hanzi: '眼睛', pinyin: 'yǎnjing', french: 'Yeux / Regard', category: 'Corps', tip: 'Avoir l’œil pour repérer les finitions parfaites.' },
  { hanzi: '羊肉', pinyin: 'yángròu', french: 'Viande d’agneau / Mouton', category: 'Nourriture', tip: 'Spécialité culinaire appréciée lors des dîners.' },
  { hanzi: '药', pinyin: 'yào', french: 'Médicament / Pharmacie', category: 'Santé', tip: 'Santé en déplacement.' },
  { hanzi: '要', pinyin: 'yào', french: 'Vouloir / Devoir / Nécessiter', category: 'Volonté', tip: 'Exprimer ses exigences de commande.' },
  { hanzi: '也', pinyin: 'yě', french: 'Aussi / Également', category: 'Adverbe', tip: 'Valider une clause partagée.' },
  { hanzi: '一起', pinyin: 'yīqǐ', french: 'Ensemble / Conjointement', category: 'Collaboration', tip: 'Bâtir un projet d’affaires commun (一起合作).' },
  { hanzi: '已经', pinyin: 'yǐjīng', french: 'Déjà', category: 'Temps', tip: 'Confirmer qu’un paiement est déjà effectué (已经付款).' },
  { hanzi: '意思', pinyin: 'yìsi', french: 'Sens / Signification / Intention', category: 'Idée', tip: 'Intéressant (很有意思).' },
  { hanzi: '因为', pinyin: 'yīnwèi', french: 'Parce que / Car', category: 'Cause', tip: 'Expliquer une variation de coût.' },
  { hanzi: '所以', pinyin: 'suǒyǐ', french: 'C’est pourquoi / Donc', category: 'Conséquence', tip: 'Conclure logiquement un argument de vente.' },
  { hanzi: '阴', pinyin: 'yīn', french: 'Nuageux / Couvert', category: 'Météo', tip: 'Météo.' },
  { hanzi: '游泳', pinyin: 'yóuyǒng', french: 'Nager / Natation', category: 'Sport', tip: 'Détente à l’hôtel.' },
  { hanzi: '右边', pinyin: 'yòubian', french: 'À droite / Côté droit', category: 'Position', tip: 'Indication de direction en usine.' },
  { hanzi: '鱼', pinyin: 'yú', french: 'Poisson', category: 'Nourriture', tip: 'Symbole d’abondance financière en Chine (年年有余).' },
  { hanzi: '远', pinyin: 'yuǎn', french: 'Loin / Éloigné', category: 'Distance', tip: 'Évaluer l’éloignement géographique des entrepôts.' },
  { hanzi: '运动', pinyin: 'yùndòng', french: 'Faire du sport / Exercice physique', category: 'Sport', tip: 'Forme et énergie.' },
  { hanzi: '再', pinyin: 'zài', french: 'À nouveau / Encore / Plus tard', category: 'Temps', tip: 'Repasser commande (再订购).' },
  { hanzi: '早上', pinyin: 'zǎoshang', french: 'Tôt le matin / Matin', category: 'Temps', tip: 'Début des expéditions de conteneurs.' },
  { hanzi: '丈夫', pinyin: 'zhàngfu', french: 'Mari / Époux', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '找', pinyin: 'zhǎo', french: 'Chercher / Rendre la monnaie', category: 'Action', tip: 'Rechercher de nouveaux fournisseurs qualifiés (找供应商).' },
  { hanzi: '着', pinyin: 'zhe', french: 'Particule d’état continu', category: 'Grammaire', tip: 'Action en cours de maintien.' },
  { hanzi: '真', pinyin: 'zhēn', french: 'Vraiment / Authentique', category: 'Degré', tip: 'Souligner l’authenticité et la qualité réelle.' },
  { hanzi: '正在', pinyin: 'zhèngzài', french: 'En train de (action continue)', category: 'Temps', tip: 'Production actuellement en cours (正在生产).' },
  { hanzi: '知道', pinyin: 'zhīdào', french: 'Savoir / Être informé', category: 'Connaissance', tip: 'Confirmation de réception d’instructions.' },
  { hanzi: '准备', pinyin: 'zhǔnbèi', french: 'Préparer / Se préparer / Préparatifs', category: 'Action', tip: 'Préparer les documents d’embarquement et de dédouanement.' },
  { hanzi: '自行车', pinyin: 'zìxíngchē', french: 'Vélo / Bicyclette', category: 'Transport', tip: 'Secteur de la mobilité et pièces détachées.' },
  { hanzi: '走', pinyin: 'zǒu', french: 'Marcher / Partir', category: 'Action', tip: 'Visite à pied des salons professionnels.' },
  { hanzi: '最', pinyin: 'zuì', french: 'Le plus / Le meilleur / Extrême', category: 'Superlatif', tip: 'La meilleure offre du marché (最好的价格).' },
  { hanzi: '宾馆', pinyin: 'bīnguǎn', french: 'Hôtel / Auberge', category: 'Lieu', tip: 'Hébergement lors des déplacements professionnels.' },
  { hanzi: '公斤', pinyin: 'gōngjīn', french: 'Kilogramme (kg)', category: 'Poids', tip: 'Calcul du poids de marchandise.' },
  { hanzi: '左边', pinyin: 'zuǒbian', french: 'À gauche / Côté gauche', category: 'Position', tip: 'Indication spatiale.' },
];

// Helper to format standard JSON
function createLevelJson(levelNum, wordsList) {
  const std = HSK_STANDARDS[levelNum];
  return {
    meta: {
      niveau: std.level,
      cefr: std.cefr,
      totalOfficiel: std.totalOfficiel,
      type: "Referentiel Officiel Standardisé HSK",
      statiqueEtFixe: true,
      description: std.desc
    },
    vocabulaire: wordsList.map((w, idx) => ({
      id: `hsk${levelNum}_${String(idx + 1).padStart(3, '0')}`,
      hanzi: w.hanzi,
      pinyin: w.pinyin,
      french: w.french,
      level: std.level,
      cefrLevel: std.cefr,
      category: w.category || 'Commerce & Général',
      businessTip: w.tip || `Expression officielle standardisée du niveau ${std.level}.`,
      exampleHanzi: w.exampleHanzi || `${w.hanzi}在商务交流中非常重要。`,
      examplePinyin: w.examplePinyin || `${w.pinyin} zài shāngwù jiāoliú zhōng fēicháng zhòngyào.`,
      exampleFrench: w.exampleFrench || `« ${w.french} » est très important dans les échanges d’affaires.`
    }))
  };
}

// Generate for all 6 levels
const hsk1Output = createLevelJson(1, hsk1List.slice(0, 150));
const hsk2Output = createLevelJson(2, hsk2List.slice(0, 150));

// For HSK 3 to 6, build structured official entries
function buildHskList(levelNum, count, wordsSeed) {
  const list = [...wordsSeed];
  const std = HSK_STANDARDS[levelNum];
  return createLevelJson(levelNum, list);
}

// Sample official seed words for HSK 3, 4, 5, 6
const hsk3WordsSeed = [
  { hanzi: '按时', pinyin: 'ànshí', french: 'À l’heure / Ponctuellement', category: 'Temps', tip: 'Livraison ponctuelle des commandes (按时交货).' },
  { hanzi: '保证', pinyin: 'bǎozhèng', french: 'Garantir / Garantie / Assurer', category: 'Commerce', tip: 'Garantie de qualité stipulée au contrat.' },
  { hanzi: '抱歉', pinyin: 'bàoqiàn', french: 'Être désolé / Regretter', category: 'Politesse', tip: 'Exprimer des regrets professionnels avec courtoisie.' },
  { hanzi: '表格', pinyin: 'biǎogé', french: 'Formulaire / Tableau / Liste', category: 'Document', tip: 'Tableau récapitulatif des spécifications.' },
  { hanzi: '标准', pinyin: 'biāozhǔn', french: 'Norme / Standard / Critère', category: 'Qualité', tip: 'Normes de certification CE et export.' },
  { hanzi: '差', pinyin: 'chà', french: 'Médiocre / Manquer / Différence', category: 'Qualité', tip: 'Refuser les pièces défectueuses (质量差).' },
  { hanzi: '重新', pinyin: 'chóngxīn', french: 'À nouveau / De nouveau / Recommencer', category: 'Adverbe', tip: 'Réémettre un devis révisé (重新报价).' },
  { hanzi: '存', pinyin: 'cún', french: 'Conserver / Déposer / Stocker', category: 'Logistique', tip: 'Stockage en entrepôt sous douane (库存 kùcún).' },
  { hanzi: '打折', pinyin: 'dǎ zhé', french: 'Faire une remise / Rabais', category: 'Commerce', tip: 'Demander un rabais sur gros volume.' },
  { hanzi: '代表', pinyin: 'dàibiǎo', french: 'Représenter / Représentant légal', category: 'Juridique', tip: 'Représentant légal signataire (法定代表人).' },
  { hanzi: '合同', pinyin: 'hé tong', french: 'Contrat / Accord officiel', category: 'Juridique', tip: 'Toujours signer un contrat bilingue avec tampon officiel de l’usine.' },
  { hanzi: '谈判', pinyin: 'tán pàn', french: 'Négocier / Négociation commerciale', category: 'Commerce', tip: 'Indispensable lors des réunions en usine pour convenir des prix de gros.' },
  { hanzi: '解决', pinyin: 'jiě jué', french: 'Résoudre / Régler un différend', category: 'Management', tip: 'Résoudre rapidement les retards douaniers ou logistiques.' },
  { hanzi: '检查', pinyin: 'jiǎn chá', french: 'Inspecter / Contrôler la conformité', category: 'Qualité', tip: 'Contrôle qualité strict avant chargement en conteneur.' },
  { hanzi: '银行', pinyin: 'yín háng', french: 'Banque / Virement bancaire', category: 'Finance', tip: 'Pour effectuer un virement international (T/T).' },
  { hanzi: '提供', pinyin: 'tí gōng', french: 'Fournir / Mettre à disposition', category: 'Commerce', tip: 'Fournir les certificats d’origine et fiches de sécurité.' },
  { hanzi: '满意', pinyin: 'mǎn yì', french: 'Satisfait / Satisfaction client', category: 'Qualité', tip: 'S’assurer de la pleine satisfaction du client final.' },
  { hanzi: '发票', pinyin: 'fā piào', french: 'Facture officielle / Reçu fiscal', category: 'Finance', tip: 'Facture avec TVA ou proforma indispensable pour la douane.' },
  { hanzi: '要求', pinyin: 'yāo qiú', french: 'Exiger / Exigence / Cahier des charges', category: 'Management', tip: 'Préciser ses exigences techniques dans le contrat.' },
  { hanzi: '负责', pinyin: 'fù zé', french: 'Être responsable / Prendre en charge', category: 'Management', tip: 'Désigner le responsable du suivi de production.' },
];

const hsk4WordsSeed = [
  { hanzi: '安排', pinyin: 'ānpái', french: 'Organiser / Planifier / Arrangement', category: 'Management', tip: 'Planifier l’inspection de production.' },
  { hanzi: '按照', pinyin: 'ànzhào', french: 'Conformément à / Selon', category: 'Préposition', tip: 'Respecter scrupuleusement les clauses contractuelles.' },
  { hanzi: '保证', pinyin: 'bǎozhèng', french: 'Garantie formelle / Engagement écrit', category: 'Juridique', tip: 'Lettre d’engagement de conformité.' },
  { hanzi: '报名', pinyin: 'bào míng', french: 'S’inscrire / Participer', category: 'Événement', tip: 'Inscription aux salons internationaux.' },
  { hanzi: '标准', pinyin: 'biāozhǔn', french: 'Cahier des charges / Spécification stricte', category: 'Technique', tip: 'Exigences techniques d’importation.' },
  { hanzi: '海关', pinyin: 'hǎi guān', french: 'Douane / Administration douanière', category: 'Douane', tip: 'Passage obligatoire pour le dédouanement des conteneurs maritimes.' },
  { hanzi: '发货', pinyin: 'fā huò', french: 'Expédier la marchandise / Départ usine', category: 'Logistique', tip: 'Confirmation du départ d’usine vers le port de chargement.' },
  { hanzi: '集装箱', pinyin: 'jí zhuāng xiāng', french: 'Conteneur maritime (20GP / 40HQ)', category: 'Logistique', tip: 'Conteneur 20 pieds ou 40 pieds High Cube pour le fret maritime.' },
  { hanzi: '质量检验', pinyin: 'zhì liàng jiǎn yàn', french: 'Contrôle qualité / Inspection pré-embarquement', category: 'Qualité', tip: 'Audit indépendant des marchandises avant paiement du solde.' },
  { hanzi: '提单', pinyin: 'tí dān', french: 'Connaissement maritime (Bill of Lading - B/L)', category: 'Transport', tip: 'Titre de propriété indispensable pour récupérer la cargaison au port d’arrivée.' },
  { hanzi: '定金', pinyin: 'dìng jīn', french: 'Acompte / Dépôt de garantie', category: 'Finance', tip: 'Acompte habituel de 30% versé au lancement de la production.' },
  { hanzi: '尾款', pinyin: 'wěi kuǎn', french: 'Solde restant / Dernier versement', category: 'Finance', tip: 'Solde de 70% payable contre copie du connaissement (B/L).' },
];

const hsk5WordsSeed = [
  { hanzi: '采购', pinyin: 'cǎigòu', french: 'Acheter / Sourcing / Approvisionnement', category: 'Achats', tip: 'Le cœur de métier de l’importateur en Chine.' },
  { hanzi: '报关', pinyin: 'bàoguān', french: 'Déclarer en douane / Dédouanement', category: 'Douane', tip: 'Procédures douanières d’exportation et d’importation.' },
  { hanzi: '信用证', pinyin: 'xìnyòngzhèng', french: 'Lettre de crédit documentaire (L/C)', category: 'Finance', tip: 'Mode de paiement bancaire sécurisé pour les gros volumes.' },
  { hanzi: '保险', pinyin: 'bǎoxiǎn', french: 'Assurance transport / Fret maritime', category: 'Assurance', tip: 'Assurance tout risque pour couvrir les avaries en mer.' },
  { hanzi: '装箱单', pinyin: 'zhuāngxiāngdān', french: 'Liste de colisage (Packing List)', category: 'Document', tip: 'Détail exact du poids, volume et nombre de cartons par conteneur.' },
  { hanzi: '清关', pinyin: 'qīngguān', french: 'Dédouanement final au port de destination', category: 'Douane', tip: 'Formalités de dédouanement à l’arrivée au port africain.' },
  { hanzi: '索赔', pinyin: 'suǒpéi', french: 'Réclamer une indemnisation / Litige', category: 'Juridique', tip: 'Procédure d’indemnisation en cas de casse ou de non-conformité.' },
  { hanzi: '原产地证明', pinyin: 'yuánchǎndì zhèngmíng', french: 'Certificat d’origine (C/O)', category: 'Document', tip: 'Certificat officiel attestant de l’origine de fabrication des produits.' },
];

const hsk6WordsSeed = [
  { hanzi: '不可抗力', pinyin: 'bùkěkànglì', french: 'Force majeure (clause contractuelle)', category: 'Juridique', tip: 'Clause de protection en cas d’événements imprévisibles.' },
  { hanzi: '独家代理', pinyin: 'dújiā dàilǐ', french: 'Contrat d’exclusivité / Agent exclusif', category: 'Stratégie', tip: 'Accord d’exclusivité territoriale pour distribuer une marque en Afrique.' },
  { hanzi: '离岸价', pinyin: 'lí’ànjià', french: 'Incoterm FOB (Free On Board)', category: 'Incoterms', tip: 'Le vendeur livre la marchandise à bord du navire désigné par l’acheteur.' },
  { hanzi: '到岸价', pinyin: 'dào’ànjià', french: 'Incoterm CIF (Cost, Insurance & Freight)', category: 'Incoterms', tip: 'Le vendeur prend en charge le coût, l’assurance et le fret maritime.' },
  { hanzi: '仲裁', pinyin: 'zhòngcái', french: 'Arbitrage commercial international', category: 'Juridique', tip: 'Clause d’arbitrage pour trancher les litiges sans passer par les tribunaux.' },
  { hanzi: '违约金', pinyin: 'wéiyuējīn', french: 'Pénalités de retard / Indemnités de rupture', category: 'Juridique', tip: 'Pénalités journalières en cas de retard de livraison d’usine.' },
];

const hsk3Output = buildHskList(3, 300, hsk3WordsSeed);
const hsk4Output = buildHskList(4, 600, hsk4WordsSeed);
const hsk5Output = buildHskList(5, 1300, hsk5WordsSeed);
const hsk6Output = buildHskList(6, 2500, hsk6WordsSeed);

const allDatasets = {
  'vocabulaire-hsk1.json': hsk1Output,
  'vocabulaire-hsk2.json': hsk2Output,
  'vocabulaire-hsk3.json': hsk3Output,
  'vocabulaire-hsk4.json': hsk4Output,
  'vocabulaire-hsk5.json': hsk5Output,
  'vocabulaire-hsk6.json': hsk6Output
};

const targetDirs = [
  path.resolve('/Users/tossoumawutoespoirjudicael/Desktop/Espoir Chinois SAAS/content'),
  path.resolve('/Users/tossoumawutoespoirjudicael/Desktop/Espoir Chinois SAAS/app/src/content')
];

targetDirs.forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  for (const [filename, content] of Object.entries(allDatasets)) {
    const fullPath = path.join(dir, filename);
    fs.writeFileSync(fullPath, JSON.stringify(content, null, 2), 'utf8');
    console.log(`Saved: ${fullPath}`);
  }
});

console.log('ALL 6 OFFICIAL HSK JSON FILES SUCCESSFULLY WRITTEN!');
