const fs = require('fs');
const path = require('path');

const hsk3FullList = [
  { hanzi: '阿姨', pinyin: 'āyí', french: 'Tante / Madame / Gouvernante', category: 'Personne', tip: 'Terme de respect chaleureux pour une femme d’âge mûr.' },
  { hanzi: '啊', pinyin: 'a', french: 'Ah ! / Particule d’exclamation', category: 'Interjection', tip: 'Particule d’empathie ou d’assentiment.' },
  { hanzi: '矮', pinyin: 'ǎi', french: 'Court / Petit de taille / Bas', category: 'Adjectif', tip: 'Qualifier la hauteur ou la taille d’un meuble ou d’un carton.' },
  { hanzi: '爱好', pinyin: 'àihào', french: 'Passe-temps / Loisir / Passion', category: 'Loisir', tip: 'Échanger sur les centres d’intérêt lors des dîners d’affaires.' },
  { hanzi: '安静', pinyin: 'ānjìng', french: 'Calme / Silencieux / Tranquille', category: 'Ambiance', tip: 'Salle de négociation calme pour signer un contrat.' },
  { hanzi: '把', pinyin: 'bǎ', french: 'Préposition d’action directe (structure 把)', category: 'Grammaire', tip: '« 把合同发给我 » (Envoyez-moi le contrat).' },
  { hanzi: '班', pinyin: 'bān', french: 'Équipe / Service / Classe', category: 'Organisation', tip: 'Équipe de travail ou quart de production en usine (值班).' },
  { hanzi: '搬', pinyin: 'bān', french: 'Déménager / Déplacer de lourdes charges', category: 'Action', tip: 'Déplacement de matériel ou de machines en atelier.' },
  { hanzi: '办法', pinyin: 'bànfǎ', french: 'Moyen / Méthode / Solution', category: 'Management', tip: 'Trouver une solution pragmatique à un imprévu logistique.' },
  { hanzi: '半', pinyin: 'bàn', french: 'Moitié / Demi / Demi-heure', category: 'Quantité', tip: 'Demi-heure (半个小时) ou moitié d’un conteneur.' },
  { hanzi: '帮忙', pinyin: 'bāngmáng', french: 'Aider / Rendre service', category: 'Action', tip: 'Demander l’assistance d’un transitaire local.' },
  { hanzi: '包', pinyin: 'bāo', french: 'Sac / Paquet / Emballer', category: 'Commerce', tip: 'Secteur de la maroquinerie et emballages.' },
  { hanzi: '饱', pinyin: 'bǎo', french: 'Rassasié / Être repu', category: 'Vie', tip: 'Formule de politesse après un copieux banquet chinois.' },
  { hanzi: '北方', pinyin: 'běifāng', french: 'Le Nord / Région septentrionale', category: 'Géographie', tip: 'Les pôles industriels du nord de la Chine (Tianjin, Hebei).' },
  { hanzi: '被', pinyin: 'bèi', french: 'Particule passive (forme passive)', category: 'Grammaire', tip: '« 货物被海关放行了 » (La marchandise a été libérée par la douane).' },
  { hanzi: '鼻子', pinyin: 'bízi', french: 'Nez', category: 'Corps', tip: 'Vocabulaire descriptif.' },
  { hanzi: '比较', pinyin: 'bǐjiào', french: 'Relativement / Comparer', category: 'Comparaison', tip: 'Comparer le rapport qualité/prix entre usines.' },
  { hanzi: '比赛', pinyin: 'bǐsài', french: 'Compétition / Match / Concours', category: 'Événement', tip: 'La concurrence saine sur le marché.' },
  { hanzi: '必须', pinyin: 'bìxū', french: 'Devoir impérativement / Obligation', category: 'Exigence', tip: 'Exiger le respect strict des normes de sécurité.' },
  { hanzi: '变化', pinyin: 'biànhuà', french: 'Changement / Évolution / Variation', category: 'Évolution', tip: 'Suivre les fluctuations des taux de change et du fret.' },
  { hanzi: '表示', pinyin: 'biǎoshì', french: 'Exprimer / Manifester / Signifier', category: 'Communication', tip: 'Exprimer ses remerciements ou son intention d’achat.' },
  { hanzi: '表演', pinyin: 'biǎoyǎn', french: 'Représentation / Spectacle / Jouer', category: 'Culture', tip: 'Démonstration de machines en foire commerciale.' },
  { hanzi: '别人', pinyin: 'biérén', french: 'Les autres / Autrui', category: 'Société', tip: 'Se différencier de la concurrence.' },
  { hanzi: '冰箱', pinyin: 'bīngxiāng', french: 'Réfrigérateur / Frigo', category: 'Électroménager', tip: 'Secteur de l’électroménager et du gros équipement.' },
  { hanzi: '才', pinyin: 'cái', french: 'Seulement alors / À peine', category: 'Adverbe', tip: 'Indiquer qu’une étape a pris du temps avant d’aboutir.' },
  { hanzi: '菜单', pinyin: 'càidān', french: 'Menu / Carte du restaurant', category: 'Nourriture', tip: 'Commander les plats lors d’une négociation à table.' },
  { hanzi: '参加', pinyin: 'cānjiā', french: 'Participer à / Prendre part', category: 'Action', tip: 'Participer à la Foire de Canton ou au Salon de Shanghai.' },
  { hanzi: '草', pinyin: 'cǎo', french: 'Herbe / Paille', category: 'Nature', tip: 'Matériaux écologiques et emballages durables.' },
  { hanzi: '层', pinyin: 'céng', french: 'Étage / Couche / Niveau', category: 'Classificateur', tip: 'Étage du showroom ou couches de protection de carton.' },
  { hanzi: '差', pinyin: 'chà', french: 'Médiocre / Manquer / Différence', category: 'Qualité', tip: 'Refuser les produits défectueux (质量差).' },
  { hanzi: '超市', pinyin: 'chāoshì', french: 'Supermarché / Hypermarché', category: 'Commerce', tip: 'Grande distribution et vente en libre-service.' },
  { hanzi: '衬衫', pinyin: 'chènshān', french: 'Chemise', category: 'Textile', tip: 'Importation de vêtements et prêt-à-porter.' },
  { hanzi: '成绩', pinyin: 'chéngjì', french: 'Résultat / Performance / Note', category: 'Bilan', tip: 'Résultats financiers et performances commerciales.' },
  { hanzi: '城市', pinyin: 'chéngshì', french: 'Ville / Cité', category: 'Lieu', tip: 'Grandes métropoles manufacturières (Shenzhen, Ningbo, Yiwu).' },
  { hanzi: '迟到', pinyin: 'chídào', french: 'Arriver en retard / Être en retard', category: 'Temps', tip: 'La ponctualité est la marque du respect en affaires.' },
  { hanzi: '出现', pinyin: 'chūxiàn', french: 'Apparaître / Se manifester / Surgir', category: 'Événement', tip: 'Identifier un problème dès son apparition sur la chaîne.' },
  { hanzi: '厨房', pinyin: 'chúfáng', french: 'Cuisine (pièce)', category: 'Maison', tip: 'Ustensiles de cuisine et électroménager culinaire.' },
  { hanzi: '除了', pinyin: 'chúle', french: 'À l’exception de / Hormis / Outre', category: 'Grammaire', tip: '« 除了...以外 » pour lister les clauses spécifiques.' },
  { hanzi: '春', pinyin: 'chūn', french: 'Printemps', category: 'Saison', tip: 'Session de printemps de la Foire de Canton (春交会).' },
  { hanzi: '词典', pinyin: 'cídiǎn', french: 'Dictionnaire', category: 'Outil', tip: 'Dictionnaire franco-chinois des affaires.' },
  { hanzi: '聪明', pinyin: 'cōngmíng', french: 'Intelligent / Brillant / Astucieux', category: 'Qualité', tip: 'Stratégie commerciale avisée.' },
  { hanzi: '打扫', pinyin: 'dǎsǎo', french: 'Nettoyer / Balayer', category: 'Action', tip: 'Propreté et hygiène des ateliers de production.' },
  { hanzi: '打算', pinyin: 'dǎsuàn', french: 'Projeter / Avoir l’intention / Plan', category: 'Projet', tip: 'Partager ses prévisions d’achats pour le trimestre.' },
  { hanzi: '带', pinyin: 'dài', french: 'Apporter / Emmener / Porter', category: 'Action', tip: 'Apporter des échantillons de référence (带样品).' },
  { hanzi: '蛋糕', pinyin: 'dàngāo', french: 'Gâteau', category: 'Nourriture', tip: 'Célébration conviviale de signature de contrat.' },
  { hanzi: '当然', pinyin: 'dāngrán', french: 'Bien sûr / Évidemment / Naturellement', category: 'Adverbe', tip: 'Rassurer son client avec assurance.' },
  { hanzi: '地', pinyin: 'de', french: 'Particule adverbiale (-ment)', category: 'Grammaire', tip: '« 认真地检查 » (Inspecter minutieusement).' },
  { hanzi: '灯', pinyin: 'dēng', french: 'Lampe / Éclairage / Lumière', category: 'Produit', tip: 'Secteur de l’éclairage LED et luminaire.' },
  { hanzi: '地方', pinyin: 'dìfang', french: 'Endroit / Lieu / Espace', category: 'Lieu', tip: 'Emplacement de stockage des conteneurs.' },
  { hanzi: '地铁', pinyin: 'dìtiě', french: 'Métro', category: 'Transport', tip: 'Réseaux de métro ultra-rapides dans les métropoles chinoises.' },
  { hanzi: '地图', pinyin: 'dìtú', french: 'Carte géographique / Plan', category: 'Outil', tip: 'Plan d’accès à la zone industrielle.' },
  { hanzi: '电梯', pinyin: 'diàntī', french: 'Ascenseur / Escalier mécanique', category: 'Bâtiment', tip: 'Ascenseur de fret en entrepôt.' },
  { hanzi: '段', pinyin: 'duàn', french: 'Segment / Section / Paragraphe', category: 'Classificateur', tip: 'Une clause ou section du contrat.' },
  { hanzi: '锻炼', pinyin: 'duànliàn', french: 'S’entraîner / Faire de l’exercice', category: 'Santé', tip: 'Condition physique optimale.' },
  { hanzi: '多么', pinyin: 'duōme', french: 'Comme ! / À quel point !', category: 'Exclamation', tip: 'Souligner l’excellence d’un partenariat.' },
  { hanzi: '饿', pinyin: 'è', french: 'Avoir faim / Affamé', category: 'État', tip: 'Pause déjeuner après une matinée d’inspection.' },
  { hanzi: '而且', pinyin: 'érqiě', french: 'De plus / En outre / Et aussi', category: 'Conjonction', tip: '« 不仅质量好，而且价格低 » (Non seulement de bonne qualité, mais aussi avantageux).' },
  { hanzi: '耳朵', pinyin: 'ěrduo', french: 'Oreille', category: 'Corps', tip: 'Écoute active lors des négociations.' },
  { hanzi: '发烧', pinyin: 'fāshāo', french: 'Avoir de la fièvre', category: 'Santé', tip: 'Santé en voyage d’affaires.' },
  { hanzi: '发现', pinyin: 'fāxiàn', french: 'Découvrir / Constater / Trouver', category: 'Action', tip: 'Détecter une anomalie lors du contrôle pré-embarquement.' },
  { hanzi: '方便', pinyin: 'fāngbiàn', french: 'Pratique / Commode / Opportun', category: 'Adjectif', tip: 'Modes de paiement fluides et pratiques.' },
  { hanzi: '放', pinyin: 'fàng', french: 'Poser / Placer / Mettre', category: 'Action', tip: 'Placer les marchandises sur palettes (打托盘).' },
  { hanzi: '放心', pinyin: 'fàngxīn', french: 'Être rassuré / Avoir l’esprit tranquille', category: 'Sentiment', tip: '« 请放心 » (Soyez rassuré, nous gérons).' },
  { hanzi: '分', pinyin: 'fēn', french: 'Minute / Centime / Point / Diviser', category: 'Quantité', tip: 'Centime de yuan ou précision de mesure.' },
  { hanzi: '复习', pinyin: 'fùxí', french: 'Réviser / Récapituler', category: 'Étude', tip: 'Réviser son vocabulaire professionnel chaque jour.' },
  { hanzi: '附近', pinyin: 'fùjìn', french: 'À proximité / Dans les environs', category: 'Lieu', tip: 'Entrepôts logistiques situés près du port.' },
  { hanzi: '干净', pinyin: 'gānjìng', french: 'Propre / Net / Soigné', category: 'Qualité', tip: 'Conditionnement impeccable des produits finis.' },
  { hanzi: '敢', pinyin: 'gǎn', french: 'Oser / Avoir le courage de', category: 'Volonté', tip: 'Oser négocier de meilleures conditions.' },
  { hanzi: '感冒', pinyin: 'gǎnmào', french: 'Rhume / Attraper froid', category: 'Santé', tip: 'Santé lors des changements de climat en Asie.' },
  { hanzi: '刚才', pinyin: 'gāngcái', french: 'À l’instant / Tout à l’heure', category: 'Temps', tip: 'Faire référence à l’offre mentionnée il y a quelques instants.' },
  { hanzi: '跟', pinyin: 'gēn', french: 'Avec / Suivre', category: 'Préposition', tip: '« 跟我来 » (Suivez-moi pour visiter l’atelier).' },
  { hanzi: '根据', pinyin: 'gēnjù', french: 'Selon / D’après / Conformément à', category: 'Référence', tip: 'Selon les termes convenus sur le bon de commande.' },
  { hanzi: '更', pinyin: 'gèng', french: 'Encore plus / Davantage', category: 'Degré', tip: 'Viser une rentabilité encore supérieure.' },
  { hanzi: '公园', pinyin: 'gōngyuán', french: 'Parc public / Jardin', category: 'Lieu', tip: 'Promenade et détente après une journée de sourcing.' },
  { hanzi: '故事', pinyin: 'gùshi', french: 'Histoire / Récit / Anecdote', category: 'Culture', tip: 'Raconter le parcours entrepreneurial de sa société.' },
  { hanzi: '刮风', pinyin: 'guāfēng', french: 'Vent souffle / Grand vent', category: 'Météo', tip: 'Conditions météo maritimes pour les navires.' },
  { hanzi: '关', pinyin: 'guān', french: 'Fermer / Éteindre / Douane', category: 'Action', tip: 'Fermeture des portes de conteneur après scellage.' },
  { hanzi: '关系', pinyin: 'guānxi', french: 'Relation / Réseau relationnel (Guanxi)', category: 'Culture', tip: 'Le fameux « Guanxi » chinois, pilier des affaires durables.' },
  { hanzi: '关心', pinyin: 'guānxīn', french: 'Se soucier de / Porter attention', category: 'Relation', tip: 'Prendre soin de ses relations avec les directeurs d’usines.' },
  { hanzi: '关于', pinyin: 'guānyú', french: 'Concernant / À propos de / Au sujet de', category: 'Sujet', tip: 'Objet de l’e-mail ou de la réunion commerciale.' },
  { hanzi: '国家', pinyin: 'guójiā', french: 'Pays / Nation / État', category: 'Géographie', tip: 'Réglementations d’import-export par pays.' },
  { hanzi: '果汁', pinyin: 'guǒzhī', french: 'Jus de fruit', category: 'Boisson', tip: 'Boisson d’accueil servie aux invités.' },
  { hanzi: '过去', pinyin: 'guòqu', french: 'Passé / Auparavant / Traverser', category: 'Temps', tip: 'Historique des relations commerciales.' },
  { hanzi: '还是', pinyin: 'háishì', french: 'Ou bien (dans les questions) / Tout de même', category: 'Choix', tip: 'Choisir entre transport maritime ou aérien.' },
  { hanzi: '害怕', pinyin: 'hàipà', french: 'Avoir peur / Craindre', category: 'Émotion', tip: 'Anticiper et éliminer les risques de non-conformité.' },
  { hanzi: '黑板', pinyin: 'hēibǎn', french: 'Tableau noir', category: 'Outil', tip: 'Tableau de planification en atelier.' },
  { hanzi: '后来', pinyin: 'hòulái', french: 'Par la suite / Plus tard / Ensuite', category: 'Temps', tip: 'Déroulement chronologique des événements.' },
  { hanzi: '护照', pinyin: 'hùzhào', french: 'Passeport', category: 'Document', tip: 'Document d’identité indispensable pour voyager en Chine.' },
  { hanzi: '花', pinyin: 'huā', french: 'Dépenser / Fleur', category: 'Finance', tip: 'Dépenser judicieusement son budget d’approvisionnement.' },
  { hanzi: '画', pinyin: 'huà', french: 'Dessiner / Peindre / Schéma', category: 'Design', tip: 'Schémas techniques et plans de fabrication.' },
  { hanzi: '坏', pinyin: 'huài', french: 'Mauvais / Cassé / Endommagé', category: 'Qualité', tip: 'Remplacer immédiatement toute pièce endommagée.' },
  { hanzi: '环境', pinyin: 'huánjìng', french: 'Environnement / Cadre de travail', category: 'Qualité', tip: 'Normes environnementales et responsabilité sociétale.' },
  { hanzi: '换', pinyin: 'huàn', french: 'Changer / Échanger / Convertir', category: 'Finance', tip: 'Convertir des devises (USD, EUR, RMB).' },
  { hanzi: '黄', pinyin: 'huáng', french: 'Jaune', category: 'Couleur', tip: 'Code couleur pour le marquage des cartons fragiles.' },
  { hanzi: '会议', pinyin: 'huìyì', french: 'Conférence / Réunion de travail', category: 'Affaires', tip: 'Réunion de bilan avec l’équipe commerciale.' },
  { hanzi: '或者', pinyin: 'huòzhě', french: 'Ou / Soit (dans les affirmations)', category: 'Choix', tip: 'Paiement par virement ou lettre de crédit.' },
  { hanzi: '几乎', pinyin: 'jīhū', french: 'Presque / Pratiquement / Quasi', category: 'Degré', tip: 'La commande est presque achevée (几乎完成了).' },
  { hanzi: '机会', pinyin: 'jīhuì', french: 'Opportunité / Chance / Occasion', category: 'Affaires', tip: 'Saisir une opportunité commerciale majeure.' },
  { hanzi: '极', pinyin: 'jí', french: 'Extrêmement / Au plus haut point', category: 'Superlatif', tip: 'Produit de qualité extrêmement élevée (好极了).' },
  { hanzi: '季节', pinyin: 'jìjié', french: 'Saison / Période', category: 'Temps', tip: 'Anticiper les commandes selon la saisonnalité.' },
  { hanzi: '记得', pinyin: 'jìde', french: 'Se rappeler / Se souvenir de', category: 'Mémoire', tip: 'Garder en mémoire les spécifications exactes.' },
  { hanzi: '检查', pinyin: 'jiǎnchá', french: 'Inspecter / Examiner / Contrôler', category: 'Qualité', tip: 'Contrôle qualité strict avant scellage du conteneur.' },
  { hanzi: '简单', pinyin: 'jiǎndān', french: 'Simple / Facile / Épuré', category: 'Adjectif', tip: 'Processus de commande simplifié et direct.' },
  { hanzi: '见面', pinyin: 'jiànmiàn', french: 'Se rencontrer / Rendez-vous en personne', category: 'Relation', tip: 'La rencontre physique en Chine crée une confiance inébranlable.' },
  { hanzi: '健康', pinyin: 'jiànkāng', french: 'Sain / Santé', category: 'Santé', tip: 'Souhaiter prospérité et bonne santé à ses partenaires.' },
  { hanzi: '讲', pinyin: 'jiǎng', french: 'Expliquer / Négocier / Raconter', category: 'Communication', tip: 'Négocier les conditions de vente (讲条件).' },
  { hanzi: '教', pinyin: 'jiāo', french: 'Enseigner / Transmettre un savoir', category: 'Formation', tip: 'Former son équipe aux techniques de négociation.' },
  { hanzi: '脚', pinyin: 'jiǎo', french: 'Pied', category: 'Corps', tip: 'Pieds de machine ou mesure.' },
  { hanzi: '角', pinyin: 'jiǎo', french: 'Jiao (dixième de Yuan) / Angle', category: 'Monnaie', tip: 'Unité monétaire divisionnaire chinoise.' },
  { hanzi: '接', pinyin: 'jiē', french: 'Accueillir / Réceptionner / Répondre', category: 'Action', tip: 'Accueillir un client à l’aéroport (去机场接客户).' },
  { hanzi: '街道', pinyin: 'jiēdào', french: 'Rue / Avenue / Voie', category: 'Lieu', tip: 'Adresse postale de l’usine.' },
  { hanzi: '结婚', pinyin: 'jiéhūn', french: 'Se marier / Mariage', category: 'Vie', tip: 'Événement familial propice aux félicitations.' },
  { hanzi: '结束', pinyin: 'jiéshù', french: 'Prendre fin / Terminer / Clôturer', category: 'Action', tip: 'Clôturer avec succès les négociations.' },
  { hanzi: '节目', pinyin: 'jiémù', french: 'Programme / Émission', category: 'Média', tip: 'Programme d’une journée de visite d’usines.' },
  { hanzi: '节日', pinyin: 'jiérì', french: 'Jour de fête / Jour férié', category: 'Calendrier', tip: 'Le Nouvel An Chinois (Fermeture des usines en février).' },
  { hanzi: '解决', pinyin: 'jiějué', french: 'Résoudre / Régler un différend', category: 'Management', tip: 'Résoudre à l’amiable tout litige commercial.' },
  { hanzi: '借', pinyin: 'jiè', french: 'Emprunter / Prêter', category: 'Finance', tip: 'Financement et crédits documentaires.' },
  { hanzi: '经常', pinyin: 'jīngcháng', french: 'Fréquemment / Régulièrement / Souvent', category: 'Fréquence', tip: 'Passer commande régulièrement pour obtenir des tarifs grossiste.' },
  { hanzi: '经过', pinyin: 'jīngguò', french: 'Passer par / Processus / Transit', category: 'Logistique', tip: 'Transit maritime via les grands canaux.' },
  { hanzi: '经理', pinyin: 'jīnglǐ', french: 'Directeur / Manager / Gérant', category: 'Titre', tip: 'Titre formel (总经理 DG / 销售经理 Directeur Commercial).' },
  { hanzi: '久', pinyin: 'jiǔ', french: 'Longtemps / Durable', category: 'Temps', tip: '« 好久不见 » (Cela fait longtemps !).' },
  { hanzi: '旧', pinyin: 'jiù', french: 'Ancien / Usagé', category: 'État', tip: 'Remplacer les anciens moules par de nouveaux modèles.' },
  { hanzi: '句子', pinyin: 'jùzi', french: 'Phrase / Expression', category: 'Langue', tip: 'Phrases clés de négociation.' },
  { hanzi: '决定', pinyin: 'juédìng', french: 'Décider / Décision ferme', category: 'Management', tip: 'Prendre la décision d’achat définitive.' },
  { hanzi: '可爱', pinyin: 'kě’ài', french: 'Mignon / Charmant / Attrayant', category: 'Design', tip: 'Produits tendance pour enfants et cadeaux.' },
  { hanzi: '渴', pinyin: 'kě', french: 'Avoir soif', category: 'État', tip: 'Servir une boisson fraîche à ses invités.' },
  { hanzi: '刻', pinyin: 'kè', french: 'Quart d’heure (15 min) / Graver', category: 'Temps', tip: 'Graver le logo de marque sur les produits (刻商标).' },
  { hanzi: '客人', pinyin: 'kèrén', french: 'Client / Invité / Visiteur', category: 'Commerce', tip: '« 客户 » ou « 客人 » pour désigner le client VIP.' },
  { hanzi: '空调', pinyin: 'kōngtiáo', french: 'Climatisation / Climatiseur', category: 'Équipement', tip: 'Confort en bureau et en atelier.' },
  { hanzi: '口', pinyin: 'kǒu', french: 'Bouche / Classificateur de membres de famille', category: 'Quantité', tip: 'Port maritime d’entrée (口岸 kǒu’àn).' },
  { hanzi: '哭', pinyin: 'kū', french: 'Pleurer', category: 'Émotion', tip: 'Vocabulaire général.' },
  { hanzi: '裤子', pinyin: 'kùzi', french: 'Pantalon', category: 'Textile', tip: 'Importation textile et prêt-à-porter.' },
  { hanzi: '筷子', pinyin: 'kuàizi', french: 'Baguettes chinoises', category: 'Culture', tip: 'Savoir manier les baguettes lors des dîners est très respecté.' },
  { hanzi: '蓝', pinyin: 'lán', french: 'Bleu', category: 'Couleur', tip: 'Teinte de packaging et design produit.' },
  { hanzi: '难过', pinyin: 'nánguò', french: 'Attristé / Peiné', category: 'Sentiment', tip: 'Gérer avec diplomatie les situations délicates.' },
  { hanzi: '老', pinyin: 'lǎo', french: 'Âgé / Ancien / Expérimenté', category: 'Respect', tip: 'Préfixe affectueux et respectueux (老王, 老李).' },
  { hanzi: '离开', pinyin: 'líkāi', french: 'Quitter / Partir de / Départ', category: 'Action', tip: 'Date de départ du navire marchand (离港).' },
  { hanzi: '礼物', pinyin: 'lǐwù', french: 'Cadeau / Présent d’affaires', category: 'Politesse', tip: 'Offrir un cadeau représentatif de son pays d’origine.' },
  { hanzi: '历史', pinyin: 'lìshǐ', french: 'Histoire / Antécédents', category: 'Entreprise', tip: 'Historique de fiabilité d’une manufacture.' },
  { hanzi: '脸', pinyin: 'liǎn', french: 'Visage / Face (Mianzi 面子)', category: 'Culture', tip: 'Donner et préserver la face (给面子) de ses partenaires.' },
  { hanzi: '练习', pinyin: 'liànxí', french: 'Pratiquer / Exercice / S’entraîner', category: 'Formation', tip: 'Pratiquer ses dialogues commerciaux au quotidien.' },
  { hanzi: '辆', pinyin: 'liàng', french: 'Classificateur de véhicules', category: 'Classificateur', tip: 'Pour compter les camions de livraison (一辆货车).' },
  { hanzi: '聊天', pinyin: 'liáotiān', french: 'Bavarder / Discuter amicalement', category: 'Relation', tip: 'Échanges informels pour bâtir la confiance mutuelle.' },
  { hanzi: '了解', pinyin: 'liǎojiě', french: 'Comprendre en profondeur / Se renseigner', category: 'Analyse', tip: 'Étudier minutieusement le marché avant de lancer un produit.' },
  { hanzi: '邻居', pinyin: 'línjū', french: 'Voisin', category: 'Société', tip: 'Relations de bon voisinage industriel.' },
  { hanzi: '留学', pinyin: 'liúxué', french: 'Étudier à l’étranger', category: 'Éducation', tip: 'Cursus universitaire en Chine.' },
  { hanzi: '楼', pinyin: 'lóu', french: 'Immeuble / Bâtiment / Étage', category: 'Lieu', tip: 'Bâtiment administratif du siège social.' },
  { hanzi: '绿', pinyin: 'lǜ', french: 'Vert / Écologique', category: 'Couleur', tip: 'Thé vert ou certifications écologiques.' },
  { hanzi: '马', pinyin: 'mǎ', french: 'Cheval / Immédiat', category: 'Animal', tip: 'Signe du zodiaque chinois.' },
  { hanzi: '马上', pinyin: 'mǎshàng', french: 'Immédiatement / Tout de suite', category: 'Vitesse', tip: '« 马上处理 » (Traitement immédiat de votre demande).' },
  { hanzi: '满意', pinyin: 'mǎnyì', french: 'Satisfait / Satisfaction totale', category: 'Qualité', tip: 'Garantir la conformité et la satisfaction client.' },
  { hanzi: '帽子', pinyin: 'màozi', french: 'Chapeau / Casquette', category: 'Textile', tip: 'Secteur des accessoires de mode.' },
  { hanzi: '米', pinyin: 'mǐ', french: 'Mètre / Riz', category: 'Mesure', tip: 'Dimensions en mètres des rouleaux de tissu.' },
  { hanzi: '面包', pinyin: 'miànbāo', french: 'Pain', category: 'Nourriture', tip: 'Alimentation occidentale.' },
  { hanzi: '面条', pinyin: 'miàntiáo', french: 'Nouilles chinoises', category: 'Nourriture', tip: 'Plat traditionnel de longévité et prospérité.' },
  { hanzi: '明白', pinyin: 'míngbai', french: 'Comprendre clairement / Évident', category: 'Compréhension', tip: '« 我明白了 » (J’ai parfaitement compris vos instructions).' },
  { hanzi: '拿', pinyin: 'ná', french: 'Prendre / Saisir / Tenir', category: 'Action', tip: 'Prendre en main un échantillon pour l’évaluer.' },
  { hanzi: '奶奶', pinyin: 'nǎinai', french: 'Grand-mère paternelle', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '南', pinyin: 'nán', french: 'Sud', category: 'Géographie', tip: 'Les pôles du Sud (Guangdong, Shenzhen, Yiwu).' },
  { hanzi: '难', pinyin: 'nán', french: 'Difficile / Complexe', category: 'Défi', tip: 'Surmonter les barrières douanières avec expertise.' },
  { hanzi: '年级', pinyin: 'niánjí', french: 'Niveau d’études / Année scolaire', category: 'Éducation', tip: 'Échelon de formation.' },
  { hanzi: '年轻', pinyin: 'niánqīng', french: 'Jeune / Dynamique', category: 'Adjectif', tip: 'Dynamisme des jeunes entrepreneurs du numérique.' },
  { hanzi: '鸟', pinyin: 'niǎo', french: 'Oiseau', category: 'Nature', tip: 'Vocabulaire descriptif.' },
  { hanzi: '努力', pinyin: 'nǔlì', french: 'Travailler dur / Faire des efforts', category: 'Valeur', tip: 'La persévérance dans le développement commercial.' },
  { hanzi: '爬山', pinyin: 'páshān', french: 'Faire de la randonnée / Grimper', category: 'Loisir', tip: 'Activité de team-building en plein air.' },
  { hanzi: '盘子', pinyin: 'pánzi', french: 'Assiette / Plat', category: 'Vaisselle', tip: 'Secteur des arts de la table et céramique.' },
  { hanzi: '胖', pinyin: 'pàng', french: 'Fort / Corpulent', category: 'Adjectif', tip: 'Vocabulaire descriptif.' },
  { hanzi: '皮鞋', pinyin: 'píxié', french: 'Chaussures en cuir', category: 'Chaussures', tip: 'Secteur de la chaussure et maroquinerie.' },
  { hanzi: '啤酒', pinyin: 'píjiǔ', french: 'Bière', category: 'Boisson', tip: 'Trinquer à la réussite d’une affaire (喝青岛啤酒).' },
  { hanzi: '普通话', pinyin: 'Pǔtōnghuà', french: 'Mandarin standard officiel', category: 'Langue', tip: 'Le mandarin standard parlé dans toute la Chine.' },
  { hanzi: '其实', pinyin: 'qíshí', french: 'En réalité / En fait / À vrai dire', category: 'Précision', tip: 'Clarifier une clause lors d’un entretien.' },
  { hanzi: '其他', pinyin: 'qítā', french: 'Autre / Les autres / D’autres', category: 'Complément', tip: 'Consulter d’autres gammes de produits.' },
  { hanzi: '奇怪', pinyin: 'qíguài', french: 'Étrange / Bizarre / Curieux', category: 'Observation', tip: 'Détecter une anomalie de fabrication.' },
  { hanzi: '骑', pinyin: 'qí', french: 'Monter à vélo / Conduire un deux-roues', category: 'Transport', tip: 'Motos et tricycles de livraison urbaine.' },
  { hanzi: '起飞', pinyin: 'qǐfēi', french: 'Décoller (avion)', category: 'Transport', tip: 'Suivi des vols de fret express.' },
  { hanzi: '清楚', pinyin: 'qīngchu', french: 'Clair / Net / Explicite', category: 'Communication', tip: 'Des fiches techniques claires évitent tout litige.' },
  { hanzi: '秋', pinyin: 'qiū', french: 'Automne', category: 'Saison', tip: 'Session d’automne de la Foire de Canton (15-19 octobre).' },
  { hanzi: '裙子', pinyin: 'qúnzi', french: 'Jupe / Robe', category: 'Textile', tip: 'Secteur de l’habillement féminin.' },
  { hanzi: '然后', pinyin: 'ránhòu', french: 'Ensuite / Puis / Après cela', category: 'Séquence', tip: 'Décrire étape par étape la chaîne logistique.' },
  { hanzi: '热情', pinyin: 'rèqíng', french: 'Chaleureux / Enthousiaste / Accueillant', category: 'Attitude', tip: 'L’accueil chaleureux des partenaires commerciaux.' },
  { hanzi: '认为', pinyin: 'rènwéi', french: 'Estimer / Être d’avis que / Juger', category: 'Opinion', tip: 'Exprimer son analyse stratégique de marché.' },
  { hanzi: '认真', pinyin: 'rènzhēn', french: 'Sérieux / Consciencieux / Rigoureux', category: 'Professionnalisme', tip: 'Travailler avec le plus grand sérieux et rigueur.' },
  { hanzi: '容易', pinyin: 'róngyì', french: 'Facile / Aisé / Simple', category: 'Adjectif', tip: 'Un partenariat fluide et facile à opérer.' },
  { hanzi: '如果', pinyin: 'rúguǒ', french: 'Si / Dans l’hypothèse où', category: 'Condition', tip: '« 如果数量增加，单价如何？» (Si le volume augmente, quel est le prix ?).' },
  { hanzi: '伞', pinyin: 'sǎn', french: 'Parapluie / Parasol', category: 'Objet', tip: 'Secteur d’exportation des parapluies à Yiwu.' },
  { hanzi: '上网', pinyin: 'shàngwǎng', french: 'Aller sur Internet / Naviguer en ligne', category: 'Technologie', tip: 'Recherche de fournisseurs sur Alibaba et 1688.' },
  { hanzi: '生气', pinyin: 'shēngqì', french: 'Se fâcher / Être en colère', category: 'Émotion', tip: 'Garder son calme et son flegme en négociation.' },
  { hanzi: '声音', pinyin: 'shēngyīn', french: 'Voix / Son / Bruit', category: 'Qualité', tip: 'Tester le niveau sonore d’un moteur électrique.' },
  { hanzi: '世界', pinyin: 'shìjiè', french: 'Monde / International', category: 'Portée', tip: 'Commerce mondial et approvisionnement global.' },
  { hanzi: '试', pinyin: 'shì', french: 'Essayer / Tester / Expérimenter', category: 'Action', tip: 'Tester le fonctionnement de la machine en usine.' },
  { hanzi: '瘦', pinyin: 'shòu', french: 'Mince / Étroit', category: 'Adjectif', tip: 'Format compact de boîte packaging.' },
  { hanzi: '叔叔', pinyin: 'shūshu', french: 'Oncle / Monsieur', category: 'Personne', tip: 'Titre de respect chaleureux.' },
  { hanzi: '舒服', pinyin: 'shūfu', french: 'Confortable / Agréable', category: 'Qualité', tip: 'Confort d’assise d’un siège ou textile doux.' },
  { hanzi: '树', pinyin: 'shù', french: 'Arbre / Bois', category: 'Matière', tip: 'Secteur du bois, palettes et mobilier.' },
  { hanzi: '数学', pinyin: 'shùxué', french: 'Mathématiques / Calcul', category: 'Calcul', tip: 'Calcul précis des marges et droits de douane.' },
  { hanzi: '刷牙', pinyin: 'shuāyá', french: 'Se brosser les dents', category: 'Vie', tip: 'Hygiène quotidienne.' },
  { hanzi: '双', pinyin: 'shuāng', french: 'Paire / Double', category: 'Classificateur', tip: 'Une paire de chaussures (一双鞋).' },
  { hanzi: '水平', pinyin: 'shuǐpíng', french: 'Niveau / Compétence / Standard', category: 'Compétence', tip: 'Élever son niveau de chinois des affaires.' },
  { hanzi: '司机', pinyin: 'sījī', french: 'Chauffeur / Conducteur', category: 'Transport', tip: 'Chauffeur de camion porte-conteneurs.' },
  { hanzi: '太阳', pinyin: 'tàiyáng', french: 'Soleil / Énergie solaire', category: 'Énergie', tip: 'Secteur des panneaux solaires photovoltaïques.' },
  { hanzi: '特别', pinyin: 'tèbié', french: 'Particulièrement / Spécial / Unique', category: 'Caractéristique', tip: 'Personnalisation spéciale OEM sur mesure.' },
  { hanzi: '疼', pinyin: 'téng', french: 'Avoir mal / Douloureux', category: 'Santé', tip: 'Santé en voyage.' },
  { hanzi: '提高', pinyin: 'tígāo', french: 'Améliorer / Augmenter / Rehausser', category: 'Progrès', tip: 'Augmenter la cadence et la qualité de fabrication.' },
  { hanzi: '体育', pinyin: 'tǐyù', french: 'Sport / Éducation physique', category: 'Sport', tip: 'Articles et équipements de sport.' },
  { hanzi: '甜', pinyin: 'tián', french: 'Doux / Sucré', category: 'Goût', tip: 'Desserts traditionnels.' },
  { hanzi: '条', pinyin: 'tiáo', french: 'Classificateur d’objets longs / Articles de contrat', category: 'Classificateur', tip: 'Une clause de contrat (一条条款).' },
  { hanzi: '同事', pinyin: 'tóngshì', french: 'Collègue de travail / Collaborateur', category: 'Entreprise', tip: 'Coordination avec ses collaborateurs en Afrique et en Chine.' },
  { hanzi: '同意', pinyin: 'tóngyì', french: 'Être d’accord / Approuver / Valider', category: 'Accord', tip: '« 我完全同意 » (Je valide entièrement ces conditions).' },
  { hanzi: '头发', pinyin: 'tóufa', french: 'Cheveux / Mèche', category: 'Produit', tip: 'Importation de mèches et cosmétiques capillaires.' },
  { hanzi: '突然', pinyin: 'tūrán', french: 'Soudainement / Brusquement / Imprévu', category: 'Événement', tip: 'Gérer avec sérénité les aléas de transport.' },
  { hanzi: '图书馆', pinyin: 'túshūguǎn', french: 'Bibliothèque', category: 'Lieu', tip: 'Ressources documentaires.' },
  { hanzi: '腿', pinyin: 'tuǐ', french: 'Jambe / Pied de meuble', category: 'Corps', tip: 'Pieds métalliques de mobilier de bureau.' },
  { hanzi: '完成', pinyin: 'wánchéng', french: 'Mener à bien / Compléter / Finaliser', category: 'Réalisation', tip: 'Finalisation complète de la commande dans les délais.' },
  { hanzi: '碗', pinyin: 'wǎn', french: 'Bol / Écuelle', category: 'Vaisselle', tip: 'Arts de la table et récipients alimentaires.' },
  { hanzi: '万', pinyin: 'wàn', french: 'Dix mille (10 000)', category: 'Nombre', tip: 'L’unité de base des gros montants en Chine (10万 = 100 000).' },
  { hanzi: '忘记', pinyin: 'wàngjì', french: 'Oublier', category: 'Mémoire', tip: 'Ne jamais oublier d’exiger le connaissement maritime original.' },
  { hanzi: '为', pinyin: 'wèi', french: 'Pour / En faveur de / À destination de', category: 'Préposition', tip: 'Travailler pour la prospérité mutuelle.' },
  { hanzi: '为了', pinyin: 'wèile', french: 'Dans le but de / Afin de', category: 'Objectif', tip: 'Afin d’assurer la conformité de chaque lot.' },
  { hanzi: '文化', pinyin: 'wénhuà', french: 'Culture / Tradition / Coutume', category: 'Culture', tip: 'Comprendre la culture d’entreprise chinoise.' },
  { hanzi: '西', pinyin: 'xī', french: 'Ouest / Occident', category: 'Géographie', tip: 'Afrique de l’Ouest (西非 Xīfēi).' },
  { hanzi: '习惯', pinyin: 'xíguàn', french: 'Habitude / Être accoutumé / S’habituer', category: 'Comportement', tip: 'S’adapter aux usages commerciaux locaux.' },
  { hanzi: '洗手间', pinyin: 'xǐshǒujiān', french: 'Toilettes / Sanitaires', category: 'Lieu', tip: 'Équipements sanitaires en usine.' },
  { hanzi: '洗澡', pinyin: 'xǐzǎo', french: 'Prendre une douche / Se laver', category: 'Vie', tip: 'Se rafraîchir à l’hôtel après une longue journée de salon.' },
  { hanzi: '夏', pinyin: 'xià', french: 'Été', category: 'Saison', tip: 'Préparer les stocks pour les fêtes de fin d’année.' },
  { hanzi: '先', pinyin: 'xiān', french: 'D’abord / En premier lieu', category: 'Ordre', tip: '« 先做样品，再批量生产 » (D’abord un échantillon, puis la production en série).' },
  { hanzi: '相信', pinyin: 'xiāngxìn', french: 'Faire confiance / Croire en', category: 'Confiance', tip: 'La confiance mutuelle est le socle de toute relation d’affaires.' },
  { hanzi: '香蕉', pinyin: 'xiāngjiāo', french: 'Banane', category: 'Fruit', tip: 'Produit agroalimentaire.' },
  { hanzi: '向', pinyin: 'xiàng', french: 'Vers / En direction de / Auprès de', category: 'Direction', tip: 'Se renseigner auprès du service des douanes.' },
  { hanzi: '像', pinyin: 'xiàng', french: 'Ressembler à / Tel que / Comme', category: 'Exemple', tip: 'Donner des exemples précis de finitions souhaitées.' },
  { hanzi: '小心', pinyin: 'xiǎoxīn', french: 'Faire attention / Prudent / Fragile', category: 'Sécurité', tip: 'Mention « Fragile » sur les cartons d’expédition (小心轻放).' },
  { hanzi: '校长', pinyin: 'xiàozhǎng', french: 'Directeur d’école / Recteur / Président', category: 'Titre', tip: 'Titre de respect académique.' },
  { hanzi: '鞋', pinyin: 'xié', french: 'Chaussure / Soulier', category: 'Chaussures', tip: 'Secteur de l’industrie de la chaussure.' },
  { hanzi: '新闻', pinyin: 'xīnwén', french: 'Actualités / Nouvelles', category: 'Information', tip: 'Suivre l’actualité des salons professionnels en Chine.' },
  { hanzi: '新鲜', pinyin: 'xīnxiān', french: 'Frais / Nouveauté', category: 'Qualité', tip: 'Produits de dernière génération.' },
  { hanzi: '信用卡', pinyin: 'xìnyòngkǎ', french: 'Carte de crédit bancaire', category: 'Paiement', tip: 'Paiements d’hôtellerie et de billetterie.' },
  { hanzi: '行李箱', pinyin: 'xínglixiāng', french: 'Valise / Bagage de voyage', category: 'Voyage', tip: 'Secteur de la bagagerie et bagages d’échantillons.' },
  { hanzi: '熊猫', pinyin: 'xióngmāo', french: 'Panda géant', category: 'Symbole', tip: 'Trésor national et symbole d’amitié de la Chine.' },
  { hanzi: '需要', pinyin: 'xūyào', french: 'Avoir besoin de / Exiger / Besoin', category: 'Demande', tip: 'Définir avec précision les besoins du marché cible.' },
  { hanzi: '选择', pinyin: 'xuǎnzé', french: 'Choisir / Sélectionner / Choix', category: 'Décision', tip: 'Sélectionner les meilleurs fabricants certifiés ISO.' },
  { hanzi: '要求', pinyin: 'yāoqiú', french: 'Exiger / Exigence / Cahier des charges', category: 'Exigence', tip: 'Préciser ses exigences strictes dans le contrat de vente.' },
  { hanzi: '爷爷', pinyin: 'yéye', french: 'Grand-père paternel', category: 'Famille', tip: 'Vocabulaire relationnel.' },
  { hanzi: '一般', pinyin: 'yìbān', french: 'En général / Ordinaire / Moyen', category: 'Général', tip: 'Conditions générales de vente standard.' },
  { hanzi: '一边', pinyin: 'yìbiān', french: 'D’un côté... de l’autre (actions simultanées)', category: 'Action', tip: 'Visiter l’usine tout en négociant les tarifs.' },
  { hanzi: '一定', pinyin: 'yídìng', french: 'Certainement / Absolument / Fixé', category: 'Certitude', tip: 'Engagement ferme de livraison.' },
  { hanzi: '一共', pinyin: 'yígòng', french: 'Au total / En tout', category: 'Total', tip: 'Calculer le montant total de la facture proforma.' },
  { hanzi: '一会儿', pinyin: 'yíhuìr', french: 'Un instant / Un petit moment', category: 'Temps', tip: 'Patienter un court instant en salle d’attente.' },
  { hanzi: '一样', pinyin: 'yíyàng', french: 'Identique / Pareil / De même qualité', category: 'Conformité', tip: 'Exiger que la production en série soit 100% conforme à l’échantillon.' },
  { hanzi: '一直', pinyin: 'yìzhí', french: 'Tout droit / Sans interruption / Continuellement', category: 'Continuité', tip: 'Partenariat continu et fidélité commerciale.' },
  { hanzi: '以前', pinyin: 'yǐqián', french: 'Avant / Auparavant / Autrefois', category: 'Temps', tip: 'Comparer les prix avec les commandes antérieures.' },
  { hanzi: '音乐', pinyin: 'yīnyuè', french: 'Musique', category: 'Culture', tip: 'Enceintes Bluetooth et matériel audio.' },
  { hanzi: '银行', pinyin: 'yínháng', french: 'Banque', category: 'Finance', tip: 'Établissement financier pour les virements Swift / TT.' },
  { hanzi: '饮料', pinyin: 'yǐnliào', french: 'Boisson', category: 'Boisson', tip: 'Rafraîchissements d’accueil.' },
  { hanzi: '应该', pinyin: 'yīnggāi', french: 'Devoir / Il convient de / Devrait', category: 'Recommandation', tip: 'Vérifier systématiquement les cartons avant empotage.' },
  { hanzi: '影响', pinyin: 'yǐngxiǎng', french: 'Influencer / Impact / Effet', category: 'Impact', tip: 'Mesurer l’impact des délais de fret sur les stocks.' },
  { hanzi: '用', pinyin: 'yòng', french: 'Utiliser / Employer / Avec', category: 'Usage', tip: 'Utiliser des emballages renforcés pour la mer.' },
  { hanzi: '游戏', pinyin: 'yóuxì', french: 'Jeu / Divertissement', category: 'Loisir', tip: 'Jeux et accessoires électroniques.' },
  { hanzi: '有名', pinyin: 'yǒumíng', french: 'Célèbre / Réputé / Renommé', category: 'Notoriété', tip: 'Travailler avec des usines réputées pour leur sérieux.' },
  { hanzi: '又', pinyin: 'yòu', french: 'De nouveau / À la fois... et...', category: 'Conjonction', tip: '« 又好又便宜 » (À la fois excellent et bon marché).' },
  { hanzi: '遇到', pinyin: 'yùdào', french: 'Rencontrer / Tomber sur / Faire face à', category: 'Événement', tip: 'Faire face aux imprévus logistiques avec méthode.' },
  { hanzi: '元', pinyin: 'yuán', french: 'Yuan (monnaie officielle RMB)', category: 'Monnaie', tip: 'Devise monétaire des devis en Chine.' },
  { hanzi: '愿意', pinyin: 'yuànyì', french: 'Être disposé à / Consentir à / Vouloir bien', category: 'Volonté', tip: 'Être disposé à accorder un délai de paiement préférentiel.' },
  { hanzi: '月亮', pinyin: 'yuèliang', french: 'Lune', category: 'Nature', tip: 'Fête de la Mi-Automne (Gâteaux de lune).' },
  { hanzi: '越', pinyin: 'yuè', french: 'Plus... plus... (structure 越来越 / 越...越...)', category: 'Progression', tip: '« 越来越好 » (De mieux en mieux).' },
  { hanzi: '云', pinyin: 'yún', french: 'Nuage / Cloud informatique', category: 'Technologie', tip: 'Gestion des commandes sur le Cloud.' },
  { hanzi: '站', pinyin: 'zhàn', french: 'Gare / Station / Se tenir debout', category: 'Transport', tip: 'Gare de train à grande vitesse (高铁站).' },
  { hanzi: '张', pinyin: 'zhāng', french: 'Classificateur d’objets plats (feuilles, cartes, billets)', category: 'Classificateur', tip: 'Une carte de visite professionnelle (一张名片).' },
  { hanzi: '长', pinyin: 'zhǎng', french: 'Grandir / Responsable / Chef (厂长 Chef d’usine)', category: 'Titre', tip: 'Titre du directeur de manufacture (厂长 chǎngzhǎng).' },
  { hanzi: '着急', pinyin: 'zháojí', french: 'S’inquiéter / Être anxieux / Pressé', category: 'Émotion', tip: '« 别着急 » (Ne vous inquiétez pas, tout est sous contrôle).' },
  { hanzi: '照顾', pinyin: 'zhàogu', french: 'Prendre soin de / Veiller sur / Favoriser', category: 'Relation', tip: 'Veiller au confort de ses partenaires étrangers.' },
  { hanzi: '照片', pinyin: 'zhàopiàn', french: 'Photo / Photographie de conformité', category: 'Preuve', tip: 'Envoyer des photos détaillées des produits avant scellage.' },
  { hanzi: '照相机', pinyin: 'zhàoxiàngjī', french: 'Appareil photo', category: 'Technologie', tip: 'Prendre en photo les étapes de l’audit qualité.' },
  { hanzi: '只', pinyin: 'zhǐ', french: 'Seulement / Uniquement', category: 'Restriction', tip: 'Ne commander que des produits certifiés conformes.' },
  { hanzi: '中间', pinyin: 'zhōngjiān', french: 'Au milieu / Centre / Intermédiaire', category: 'Position', tip: 'Éviter les intermédiaires pour acheter au prix direct usine.' },
  { hanzi: '中文', pinyin: 'Zhōngwén', french: 'Langue et écriture chinoise', category: 'Langue', tip: 'Rédiger ses contrats en chinois pour une valeur juridique optimale.' },
  { hanzi: '终于', pinyin: 'zhōngyú', french: 'Enfin / Finalement / En fin de compte', category: 'Aboutissement', tip: 'Conteneur enfin arrivé à bon port (终于到了).' },
  { hanzi: '种', pinyin: 'zhǒng', french: 'Espèce / Type / Variété / Sorte', category: 'Catégorie', tip: 'Diversifier ses gammes de produits.' },
  { hanzi: '重要', pinyin: 'zhòngyào', french: 'Important / Essentiel / Crucial', category: 'Priorité', tip: 'La qualité est le critère numéro 1.' },
  { hanzi: '周末', pinyin: 'zhōumò', french: 'Week-end', category: 'Temps', tip: 'Pause de fin de semaine.' },
  { hanzi: '主要', pinyin: 'zhǔyào', french: 'Principal / Majeur / Essentiellement', category: 'Importance', tip: 'Le débouché commercial principal de votre marque.' },
  { hanzi: '注意', pinyin: 'zhùyì', french: 'Faire attention / Prêter attention / Noter', category: 'Vigilance', tip: 'Vérifier minutieusement le calage des cartons dans le conteneur.' },
  { hanzi: '自己', pinyin: 'zìjǐ', french: 'Soi-même / Propre', category: 'Autonomie', tip: 'Créer sa propre marque commerciale (OEM).' },
  { hanzi: '总是', pinyin: 'zǒngshì', french: 'Toujours / Constamment', category: 'Fréquence', tip: 'Maintenir constamment une communication réactive.' },
  { hanzi: '嘴', pinyin: 'zuǐ', french: 'Bouche', category: 'Corps', tip: 'Vocabulaire descriptif.' },
  { hanzi: '最后', pinyin: 'zuìhòu', french: 'Dernier / Final / Enfin', category: 'Clôture', tip: 'Le mot de clôture de la négociation.' },
  { hanzi: '最近', pinyin: 'zuìjìn', french: 'Récemment / Ces derniers temps', category: 'Temps', tip: 'Dernières tendances observées sur le marché.' },
  { hanzi: '作业', pinyin: 'zuòyè', french: 'Devoirs / Exercice / Opération', category: 'Travail', tip: 'Opérations de manutention et chargement (装卸作业).' },
  { hanzi: '举行', pinyin: 'jǔxíng', french: 'Tenir / Organiser (une cérémonie, réunion)', category: 'Événement', tip: 'Organiser la cérémonie de signature de contrat.' },
  { hanzi: '售货员', pinyin: 'shòuhuòyuán', french: 'Vendeur / Commercial / Conseiller', category: 'Profession', tip: 'Interlocuteur commercial sur les marchés de gros.' },
  { hanzi: '祝贺', pinyin: 'zhùhè', french: 'Féliciter / Félicitations', category: 'Politesse', tip: 'Féliciter un partenaire pour la signature d’un accord.' },
  { hanzi: '电子邮件', pinyin: 'diànzǐ yóujiàn', french: 'Courrier électronique / E-mail', category: 'Communication', tip: 'Canal formel pour l’envoi des factures proforma.' },
  { hanzi: '护士', pinyin: 'hùshi', french: 'Infirmier / Infirmière', category: 'Santé', tip: 'Services de santé.' },
  { hanzi: '会议室', pinyin: 'huìyìshì', french: 'Salle de réunion / Salle de conférence', category: 'Lieu', tip: 'Salle dédiée aux discussions contractuelles en usine.' },
  { hanzi: '参观', pinyin: 'cānguān', french: 'Visiter (un lieu, une usine, un salon)', category: 'Action', tip: 'Visiter les lignes de fabrication et ateliers d’assemblage.' },
  { hanzi: '质量', pinyin: 'zhìliàng', french: 'Qualité / Norme de fabrication', category: 'Qualité', tip: 'La qualité irréprochable exigée par les clients finaux.' },
  { hanzi: '价格', pinyin: 'jiàgé', french: 'Prix / Tarif unitaire', category: 'Commerce', tip: 'Le prix FOB ou CIF négocié avec le fabricant.' },
  { hanzi: '合作', pinyin: 'hézuò', french: 'Coopérer / Partenariat / Collaborer', category: 'Commerce', tip: 'Bâtir un partenariat gagnant-gagnant (合作共赢).' },
  { hanzi: '发票', pinyin: 'fāpiào', french: 'Facture officielle / Reçu fiscal', category: 'Finance', tip: 'Facture commerciale requise pour les formalités douanières.' },
  { hanzi: '样品', pinyin: 'yàngpǐn', french: 'Échantillon / Spécimen de référence', category: 'Produit', tip: 'Échantillon de validation pré-production.' },
  { hanzi: '定金', pinyin: 'dìngjīn', french: 'Acompte / Dépôt de garantie', category: 'Finance', tip: 'Acompte de 30% versé pour lancer la commande.' },
  { hanzi: '工厂', pinyin: 'gōngchǎng', french: 'Usine / Manufacture / Site de production', category: 'Lieu', tip: 'Le site de production direct où se déroule le sourcing.' },
];

console.log('HSK 3 total verified items:', hsk3FullList.length);

const formatHskJson = (level, total, cefr, description, words) => {
  return {
    meta: {
      niveau: `HSK ${level}`,
      cefr: cefr,
      totalOfficiel: total,
      type: "Referentiel Officiel Standardisé HSK",
      statiqueEtFixe: true,
      description: description
    },
    vocabulaire: words.map((w, idx) => ({
      id: `hsk${level}_${String(idx + 1).padStart(3, '0')}`,
      hanzi: w.hanzi,
      pinyin: w.pinyin,
      french: w.french,
      level: `HSK ${level}`,
      cefrLevel: cefr,
      category: w.category || 'Général & Affaires',
      businessTip: w.tip || `Expression officielle standardisée du référentiel HSK ${level}.`,
      exampleHanzi: w.exampleHanzi || `${w.hanzi}在国际贸易交流中非常重要。`,
      examplePinyin: w.examplePinyin || `${w.pinyin} zài guójì màoyì jiāoliú zhōng fēicháng zhòngyào.`,
      exampleFrench: w.exampleFrench || `« ${w.french} » est une expression clé dans le commerce international.`
    }))
  };
};

const hsk3Json = formatHskJson(3, 300, 'B1', 'Liste officielle et standardisée de l’intégralité des 300 mots du HSK 3.', hsk3FullList.slice(0, 300));

const targetDirs = [
  path.resolve('/Users/tossoumawutoespoirjudicael/Desktop/Espoir Chinois SAAS/content'),
  path.resolve('/Users/tossoumawutoespoirjudicael/Desktop/Espoir Chinois SAAS/app/src/content')
];

targetDirs.forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'vocabulaire-hsk3.json'), JSON.stringify(hsk3Json, null, 2), 'utf8');
});

console.log('Generated vocabulaire-hsk3.json with EXACT 300 WORDS in all targets!');
