export type BadgeCategory = 'tous' | 'debutant' | 'series' | 'vocabulaire' | 'immersion' | 'exercices' | 'temps' | 'business';

export type BadgeTier = 'bronze' | 'argent' | 'or' | 'diamant' | 'supreme';

export interface BadgeDefinition {
  id: string;
  title: string;
  description: string;
  category: BadgeCategory;
  tier: BadgeTier;
  icon: string;
  xpReward: number;
  conditionDescription: string;
  maxProgress: number;
  targetUnit: string;
  trackId: string; // Identifiant de la filière
  trackName: string; // Nom de la filière
  stepInTrack: number; // Étape 1, 2, 3...
  totalStepsInTrack: number;
}

export interface UserBadgeProgress extends BadgeDefinition {
  isUnlocked: boolean;
  unlockedAt?: string | null;
  currentProgress: number;
  progressPercent: number;
}

export const ALL_BADGES: BadgeDefinition[] = [
  // =========================================================================
  // ⏱️ FILIÈRE 1 : TEMPS D'ÉTUDE & PERSÉVÉRANCE (Progression en heures)
  // =========================================================================
  {
    id: 'study_time_30m',
    title: 'Premier Éveil',
    description: 'Cumuler vos premières 30 minutes d’apprentissage actif.',
    category: 'temps',
    tier: 'bronze',
    icon: '🌱',
    xpReward: 50,
    conditionDescription: '30 minutes d’étude',
    maxProgress: 30,
    targetUnit: 'minutes',
    trackId: 'track_study_time',
    trackName: 'Temps d’Étude & Persévérance',
    stepInTrack: 1,
    totalStepsInTrack: 7,
  },
  {
    id: 'study_time_2h',
    title: 'Fondations Solides',
    description: 'Cumuler 2 heures d’apprentissage du mandarin sur ChinoisLingo.',
    category: 'temps',
    tier: 'bronze',
    icon: '⏳',
    xpReward: 100,
    conditionDescription: '2 heures d’étude (120 min)',
    maxProgress: 120,
    targetUnit: 'minutes',
    trackId: 'track_study_time',
    trackName: 'Temps d’Étude & Persévérance',
    stepInTrack: 2,
    totalStepsInTrack: 7,
  },
  {
    id: 'study_time_5h',
    title: 'Pratiquant Régulier',
    description: 'Atteindre le palier symbolique des 5 heures de pratique.',
    category: 'temps',
    tier: 'argent',
    icon: '⏱️',
    xpReward: 250,
    conditionDescription: '5 heures d’étude (300 min)',
    maxProgress: 300,
    targetUnit: 'minutes',
    trackId: 'track_study_time',
    trackName: 'Temps d’Étude & Persévérance',
    stepInTrack: 3,
    totalStepsInTrack: 7,
  },
  {
    id: 'study_time_10h',
    title: 'Immersion Approfondie',
    description: '10 heures de formation, vocabulaire et écoute active.',
    category: 'temps',
    tier: 'argent',
    icon: '🧠',
    xpReward: 500,
    conditionDescription: '10 heures d’étude (600 min)',
    maxProgress: 600,
    targetUnit: 'minutes',
    trackId: 'track_study_time',
    trackName: 'Temps d’Étude & Persévérance',
    stepInTrack: 4,
    totalStepsInTrack: 7,
  },
  {
    id: 'study_time_25h',
    title: 'Discipline de Fer',
    description: '25 heures d’immersion totale. Le mandarin devient un réflexe.',
    category: 'temps',
    tier: 'or',
    icon: '🛡️',
    xpReward: 1000,
    conditionDescription: '25 heures d’étude (1500 min)',
    maxProgress: 1500,
    targetUnit: 'minutes',
    trackId: 'track_study_time',
    trackName: 'Temps d’Étude & Persévérance',
    stepInTrack: 5,
    totalStepsInTrack: 7,
  },
  {
    id: 'study_time_50h',
    title: 'Expert de l’Immersion',
    description: '50 heures de pratique active en chinois.',
    category: 'temps',
    tier: 'diamant',
    icon: '💎',
    xpReward: 2000,
    conditionDescription: '50 heures d’étude (3000 min)',
    maxProgress: 3000,
    targetUnit: 'minutes',
    trackId: 'track_study_time',
    trackName: 'Temps d’Étude & Persévérance',
    stepInTrack: 6,
    totalStepsInTrack: 7,
  },
  {
    id: 'study_time_100h',
    title: 'Grand Maître Centurion',
    description: '100 heures d’apprentissage. Maîtrise exceptionnelle du mandarin.',
    category: 'temps',
    tier: 'supreme',
    icon: '👑',
    xpReward: 5000,
    conditionDescription: '100 heures d’étude (6000 min)',
    maxProgress: 6000,
    targetUnit: 'minutes',
    trackId: 'track_study_time',
    trackName: 'Temps d’Étude & Persévérance',
    stepInTrack: 7,
    totalStepsInTrack: 7,
  },

  // =========================================================================
  // 🔥 FILIÈRE 2 : FLAMMES & SÉRIES QUOTIDIENNES (Progression en jours)
  // =========================================================================
  {
    id: 'streak_3_days',
    title: 'Étincelle d’Assiduité',
    description: 'Maintenir une série d’apprentissage de 3 jours consécutifs.',
    category: 'series',
    tier: 'bronze',
    icon: '✨',
    xpReward: 100,
    conditionDescription: 'Série de 3 jours consécutifs',
    maxProgress: 3,
    targetUnit: 'jours',
    trackId: 'track_streaks',
    trackName: 'Régularité & Flammes',
    stepInTrack: 1,
    totalStepsInTrack: 7,
  },
  {
    id: 'streak_7_days',
    title: 'Flamme de 7 jours',
    description: 'Une semaine entière de pratique quotidienne sans interruption.',
    category: 'series',
    tier: 'argent',
    icon: '🔥',
    xpReward: 250,
    conditionDescription: 'Série de 7 jours consécutifs',
    maxProgress: 7,
    targetUnit: 'jours',
    trackId: 'track_streaks',
    trackName: 'Régularité & Flammes',
    stepInTrack: 2,
    totalStepsInTrack: 7,
  },
  {
    id: 'streak_14_days',
    title: 'Habitude d’Acier',
    description: 'Deux semaines complètes d’immersion active en mandarin.',
    category: 'series',
    tier: 'argent',
    icon: '⚡',
    xpReward: 500,
    conditionDescription: 'Série de 14 jours consécutifs',
    maxProgress: 14,
    targetUnit: 'jours',
    trackId: 'track_streaks',
    trackName: 'Régularité & Flammes',
    stepInTrack: 3,
    totalStepsInTrack: 7,
  },
  {
    id: 'streak_30_days',
    title: 'Légende d’un Mois',
    description: '30 jours consécutifs de régularité absolue.',
    category: 'series',
    tier: 'or',
    icon: '🏆',
    xpReward: 1000,
    conditionDescription: 'Série de 30 jours consécutifs',
    maxProgress: 30,
    targetUnit: 'jours',
    trackId: 'track_streaks',
    trackName: 'Régularité & Flammes',
    stepInTrack: 4,
    totalStepsInTrack: 7,
  },
  {
    id: 'streak_60_days',
    title: 'Pilier de Constance',
    description: '60 jours consécutifs (2 mois complets) sans interruption.',
    category: 'series',
    tier: 'or',
    icon: '🌟',
    xpReward: 2000,
    conditionDescription: 'Série de 60 jours consécutifs',
    maxProgress: 60,
    targetUnit: 'jours',
    trackId: 'track_streaks',
    trackName: 'Régularité & Flammes',
    stepInTrack: 5,
    totalStepsInTrack: 7,
  },
  {
    id: 'streak_100_days',
    title: 'Centenaire du Mandarin',
    description: '100 jours de série ininterrompue. L’excellence au quotidien.',
    category: 'series',
    tier: 'diamant',
    icon: '💎',
    xpReward: 3500,
    conditionDescription: 'Série de 100 jours consécutifs',
    maxProgress: 100,
    targetUnit: 'jours',
    trackId: 'track_streaks',
    trackName: 'Régularité & Flammes',
    stepInTrack: 6,
    totalStepsInTrack: 7,
  },
  {
    id: 'streak_365_days',
    title: 'Légende Annuelle',
    description: '365 jours de chinois sans faille (1 an d’apprentissage).',
    category: 'series',
    tier: 'supreme',
    icon: '🐉',
    xpReward: 10000,
    conditionDescription: 'Série de 365 jours consécutifs',
    maxProgress: 365,
    targetUnit: 'jours',
    trackId: 'track_streaks',
    trackName: 'Régularité & Flammes',
    stepInTrack: 7,
    totalStepsInTrack: 7,
  },

  // =========================================================================
  // 📚 FILIÈRE 3 : MAÎTRISE DU VOCABULAIRE & COMBINAISON (Progression en mots)
  // =========================================================================
  {
    id: 'words_1',
    title: 'Premier Mot Mémorisé',
    description: 'Enregistrer votre tout 1er mot dans Mes Mots.',
    category: 'vocabulaire',
    tier: 'bronze',
    icon: '🌱',
    xpReward: 50,
    conditionDescription: '1 mot enregistré',
    maxProgress: 1,
    targetUnit: 'mot',
    trackId: 'track_vocab',
    trackName: 'Maîtrise du Vocabulaire',
    stepInTrack: 1,
    totalStepsInTrack: 7,
  },
  {
    id: 'words_25',
    title: 'Explorateur de Mots',
    description: '25 mots chinois enregistrés pour communiquer au quotidien.',
    category: 'vocabulaire',
    tier: 'bronze',
    icon: '📖',
    xpReward: 150,
    conditionDescription: '25 mots enregistrés',
    maxProgress: 25,
    targetUnit: 'mots',
    trackId: 'track_vocab',
    trackName: 'Maîtrise du Vocabulaire',
    stepInTrack: 2,
    totalStepsInTrack: 7,
  },
  {
    id: 'words_50',
    title: 'Collectionneur Assidu',
    description: '50 mots enregistrés et intégrés par combinaison.',
    category: 'vocabulaire',
    tier: 'argent',
    icon: '📚',
    xpReward: 300,
    conditionDescription: '50 mots enregistrés',
    maxProgress: 50,
    targetUnit: 'mots',
    trackId: 'track_vocab',
    trackName: 'Maîtrise du Vocabulaire',
    stepInTrack: 3,
    totalStepsInTrack: 7,
  },
  {
    id: 'words_100',
    title: 'Maître des 100 Mots (HSK 1)',
    description: '100 mots chinois maîtrisés. Le socle du HSK 1 est posé.',
    category: 'vocabulaire',
    tier: 'argent',
    icon: '🏆',
    xpReward: 600,
    conditionDescription: '100 mots enregistrés',
    maxProgress: 100,
    targetUnit: 'mots',
    trackId: 'track_vocab',
    trackName: 'Maîtrise du Vocabulaire',
    stepInTrack: 4,
    totalStepsInTrack: 7,
  },
  {
    id: 'words_250',
    title: 'Passeport HSK 2',
    description: '250 mots enregistrés. Capacité à dialoguer en situation réelle.',
    category: 'vocabulaire',
    tier: 'or',
    icon: '🚀',
    xpReward: 1200,
    conditionDescription: '250 mots enregistrés',
    maxProgress: 250,
    targetUnit: 'mots',
    trackId: 'track_vocab',
    trackName: 'Maîtrise du Vocabulaire',
    stepInTrack: 5,
    totalStepsInTrack: 7,
  },
  {
    id: 'words_500',
    title: 'Lexicologue HSK 3',
    description: '500 mots chinois enregistrés. Autonomie avancée à l’oral.',
    category: 'vocabulaire',
    tier: 'diamant',
    icon: '💎',
    xpReward: 2500,
    conditionDescription: '500 mots enregistrés',
    maxProgress: 500,
    targetUnit: 'mots',
    trackId: 'track_vocab',
    trackName: 'Maîtrise du Vocabulaire',
    stepInTrack: 6,
    totalStepsInTrack: 7,
  },
  {
    id: 'words_1000',
    title: 'Grand Érudit du Mandarin',
    description: '1000 mots chinois enregistrés et révisés avec rigueur.',
    category: 'vocabulaire',
    tier: 'supreme',
    icon: '👑',
    xpReward: 5000,
    conditionDescription: '1000 mots enregistrés',
    maxProgress: 1000,
    targetUnit: 'mots',
    trackId: 'track_vocab',
    trackName: 'Maîtrise du Vocabulaire',
    stepInTrack: 7,
    totalStepsInTrack: 7,
  },

  // =========================================================================
  // 🎧 FILIÈRE 4 : ÉCOUTE, MUSIQUE & IMMERSION CULTURELLE (Jusqu'à 100 contenus)
  // =========================================================================
  {
    id: 'first_immersion',
    title: 'Première Immersion',
    description: 'Compléter une première histoire, dialogue ou chanson.',
    category: 'immersion',
    tier: 'bronze',
    icon: '🎧',
    xpReward: 50,
    conditionDescription: '1 ressource audio complétée',
    maxProgress: 1,
    targetUnit: 'ressource',
    trackId: 'track_immersion',
    trackName: 'Immersion & Écoute',
    stepInTrack: 1,
    totalStepsInTrack: 6,
  },
  {
    id: 'music_lover',
    title: 'Mélomane Chinois',
    description: 'Écouter et marquer comme terminées 5 chansons chinoises.',
    category: 'immersion',
    tier: 'bronze',
    icon: '🎵',
    xpReward: 200,
    conditionDescription: '5 chansons terminées',
    maxProgress: 5,
    targetUnit: 'chansons',
    trackId: 'track_immersion',
    trackName: 'Immersion & Écoute',
    stepInTrack: 2,
    totalStepsInTrack: 6,
  },
  {
    id: 'avid_reader',
    title: 'Lecteur Passionné',
    description: 'Compléter 15 histoires ou articles en immersion bilingue.',
    category: 'immersion',
    tier: 'argent',
    icon: '📜',
    xpReward: 500,
    conditionDescription: '15 lectures complétées',
    maxProgress: 15,
    targetUnit: 'lectures',
    trackId: 'track_immersion',
    trackName: 'Immersion & Écoute',
    stepInTrack: 3,
    totalStepsInTrack: 6,
  },
  {
    id: 'auditor_30',
    title: 'Auditeur Assidu',
    description: 'Compléter 30 ressources audio et lectures immersives.',
    category: 'immersion',
    tier: 'argent',
    icon: '🎙️',
    xpReward: 1000,
    conditionDescription: '30 ressources complétées',
    maxProgress: 30,
    targetUnit: 'ressources',
    trackId: 'track_immersion',
    trackName: 'Immersion & Écoute',
    stepInTrack: 4,
    totalStepsInTrack: 6,
  },
  {
    id: 'auditor_60',
    title: 'Connaisseur des Médias',
    description: '60 ressources complétées (dialogues, chansons, podcasts).',
    category: 'immersion',
    tier: 'or',
    icon: '📻',
    xpReward: 2000,
    conditionDescription: '60 ressources complétées',
    maxProgress: 60,
    targetUnit: 'ressources',
    trackId: 'track_immersion',
    trackName: 'Immersion & Écoute',
    stepInTrack: 5,
    totalStepsInTrack: 6,
  },
  {
    id: 'immersion_master_100',
    title: 'Grand Maître de l’Immersion',
    description: '100 contenus multimédias complétés du catalogue.',
    category: 'immersion',
    tier: 'supreme',
    icon: '🌟',
    xpReward: 4000,
    conditionDescription: '100 ressources complétées',
    maxProgress: 100,
    targetUnit: 'ressources',
    trackId: 'track_immersion',
    trackName: 'Immersion & Écoute',
    stepInTrack: 6,
    totalStepsInTrack: 6,
  },

  // =========================================================================
  // 💼 FILIÈRE 5 : BUSINESS, MARCHÉS & NÉGOCIATION EN CHINE (Titres valorisants)
  // =========================================================================
  {
    id: 'business_starter',
    title: 'Premier Pas dans les Affaires',
    description: 'Cumuler 1 heure d’immersion pour préparer vos échanges commerciaux.',
    category: 'business',
    tier: 'bronze',
    icon: '🤝',
    xpReward: 100,
    conditionDescription: '1 heure d’étude (60 min)',
    maxProgress: 60,
    targetUnit: 'minutes',
    trackId: 'track_business',
    trackName: 'Business & Négociation',
    stepInTrack: 1,
    totalStepsInTrack: 4,
  },
  {
    id: 'business_trade_practice',
    title: 'Pratique des Échanges Commerciaux',
    description: 'Cumuler 5 heures d’apprentissage (vocabulaire usine, devis, commandes).',
    category: 'business',
    tier: 'argent',
    icon: '💼',
    xpReward: 400,
    conditionDescription: '5 heures d’étude (300 min)',
    maxProgress: 300,
    targetUnit: 'minutes',
    trackId: 'track_business',
    trackName: 'Business & Négociation',
    stepInTrack: 2,
    totalStepsInTrack: 4,
  },
  {
    id: 'business_negotiation_mastery',
    title: 'Maîtrise des Négociations',
    description: 'Cumuler 15 heures d’apprentissage pour négocier avec aisance et assurance.',
    category: 'business',
    tier: 'or',
    icon: '📈',
    xpReward: 1200,
    conditionDescription: '15 heures d’étude (900 min)',
    maxProgress: 900,
    targetUnit: 'minutes',
    trackId: 'track_business',
    trackName: 'Business & Négociation',
    stepInTrack: 3,
    totalStepsInTrack: 4,
  },
  {
    id: 'business_china_expertise',
    title: 'Expertise Business Chine',
    description: 'Cumuler 40 heures d’expertise commerciale et linguistique approfondie.',
    category: 'business',
    tier: 'diamant',
    icon: '🏆',
    xpReward: 3500,
    conditionDescription: '40 heures d’étude (2400 min)',
    maxProgress: 2400,
    targetUnit: 'minutes',
    trackId: 'track_business',
    trackName: 'Business & Négociation',
    stepInTrack: 4,
    totalStepsInTrack: 4,
  },

  // =========================================================================
  // ❄️ FILIÈRE 6 : SÉCURITÉ & BOUCLIERS DE GLACE
  // =========================================================================
  {
    id: 'streak_freeze_guardian',
    title: 'Bouclier de Glace',
    description: 'Disposer de la protection active du Gel de Série ❄️.',
    category: 'series',
    tier: 'argent',
    icon: '❄️',
    xpReward: 150,
    conditionDescription: 'Protection de série active',
    maxProgress: 1,
    targetUnit: 'protection',
    trackId: 'track_streaks',
    trackName: 'Régularité & Flammes',
    stepInTrack: 1,
    totalStepsInTrack: 1,
  },

  // =========================================================================
  // 🎧 FILIÈRE 7 : EXERCICES & ÉCOUTE HSK
  // =========================================================================
  {
    id: 'hsk_exercise_first',
    title: 'Premier Pas HSK',
    description: 'Compléter votre toute première série d’exercices d’écoute HSK.',
    category: 'exercices',
    tier: 'bronze',
    icon: '🌱',
    xpReward: 50,
    conditionDescription: '1 série complétée',
    maxProgress: 1,
    targetUnit: 'séries',
    trackId: 'track_hsk_exercises',
    trackName: 'Exercices & Écoute HSK',
    stepInTrack: 1,
    totalStepsInTrack: 5,
  },
  {
    id: 'hsk_exercise_perfect',
    title: 'Oreille Absolue',
    description: 'Obtenir un score parfait de 100% de réussite sur une série d’exercices HSK.',
    category: 'exercices',
    tier: 'argent',
    icon: '🎯',
    xpReward: 250,
    conditionDescription: '1 score parfait (100%)',
    maxProgress: 1,
    targetUnit: 'séries',
    trackId: 'track_hsk_exercises',
    trackName: 'Exercices & Écoute HSK',
    stepInTrack: 2,
    totalStepsInTrack: 5,
  },
  {
    id: 'hsk_exercise_5_series',
    title: 'Praticien de l’Écoute',
    description: 'Réussir 5 séries d’exercices HSK en obtenant au moins deux tiers des points.',
    category: 'exercices',
    tier: 'argent',
    icon: '⚡',
    xpReward: 250,
    conditionDescription: '5 séries réussies (≥ 70%)',
    maxProgress: 5,
    targetUnit: 'séries',
    trackId: 'track_hsk_exercises',
    trackName: 'Exercices & Écoute HSK',
    stepInTrack: 3,
    totalStepsInTrack: 5,
  },
  {
    id: 'hsk_exercise_15_series',
    title: 'Expert de l’Écoute',
    description: 'Réussir 15 séries d’exercices HSK en obtenant au moins deux tiers des points.',
    category: 'exercices',
    tier: 'or',
    icon: '🛡️',
    xpReward: 1000,
    conditionDescription: '15 séries réussies (≥ 70%)',
    maxProgress: 15,
    targetUnit: 'séries',
    trackId: 'track_hsk_exercises',
    trackName: 'Exercices & Écoute HSK',
    stepInTrack: 4,
    totalStepsInTrack: 5,
  },
  {
    id: 'hsk_exercise_30_series',
    title: 'Maître de la Compréhension',
    description: 'Réussir 30 séries d’exercices HSK en obtenant au moins deux tiers des points.',
    category: 'exercices',
    tier: 'diamant',
    icon: '💎',
    xpReward: 2500,
    conditionDescription: '30 séries réussies (≥ 70%)',
    maxProgress: 30,
    targetUnit: 'séries',
    trackId: 'track_hsk_exercises',
    trackName: 'Exercices & Écoute HSK',
    stepInTrack: 5,
    totalStepsInTrack: 5,
  },
];
